import type { CourseModule, Lesson, SkillLine, SkillLineId } from "./types";

export const skillLines: SkillLine[] = [
  {
    id: "data-review",
    title: "数据审查",
    shortTitle: "数据",
    description: "检查 ticker、交易日、OHLCV、复权列、缺失和选择偏差，让后续指标有可信输入。",
    capstoneEvidence: "报告说明数据范围、复权列选择、缺失值、异常值和样本选择限制。",
  },
  {
    id: "return-path",
    title: "收益路径",
    shortTitle: "收益",
    description: "把价格转换为收益率、复利净值、年化收益和回撤路径，不只看最终数字。",
    capstoneEvidence: "报告展示价格、日收益、净值和回撤，并解释路径风险。",
  },
  {
    id: "risk-reading",
    title: "风险解释",
    shortTitle: "风险",
    description: "读懂波动、最大回撤、夏普、胜率和盈亏比，并知道每个指标会怎样误导。",
    capstoneEvidence: "报告给出绩效指标表，并写出至少 3 个指标局限。",
  },
  {
    id: "execution-assumptions",
    title: "执行假设",
    shortTitle: "执行",
    description: "区分 signal、position、lag、turnover、commission 和 slippage，避免把想法直接当收益。",
    capstoneEvidence: "报告说明仓位滞后、成本假设、换手和向量化回测简化边界。",
  },
  {
    id: "validation",
    title: "验证能力",
    shortTitle: "验证",
    description: "用错误回测、参数扫描、样本外和随机策略识别过拟合与数据窥探。",
    capstoneEvidence: "报告包含参数扫描、样本内 / 样本外和偏差检查。",
  },
  {
    id: "research-writing",
    title: "研究表达",
    shortTitle: "报告",
    description: "把代码、图表、测试和限制写成可复查的学习报告，避免收益承诺式表述。",
    capstoneEvidence: "报告语言明确教育用途、非投资建议和历史结果不代表未来。",
  },
];

const moduleSkillLines: Record<string, SkillLineId[]> = {
  m0: ["research-writing", "return-path"],
  m1: ["data-review"],
  m2: ["return-path"],
  m3: ["risk-reading"],
  m4: ["execution-assumptions", "validation"],
  m5: ["return-path", "execution-assumptions", "research-writing"],
  m6: ["execution-assumptions", "validation"],
  m7: ["data-review", "risk-reading"],
  m8: ["validation"],
  m9: ["research-writing", "validation"],
};

const lessonSkillOverrides: Record<string, SkillLineId> = {
  "project-boundary": "research-writing",
  "codex-workflow": "research-writing",
  "first-tested-function": "return-path",
  "ohlcv-data": "data-review",
  "adjusted-close": "data-review",
  "data-quality": "data-review",
  "max-drawdown": "risk-reading",
  "sharpe-ratio": "risk-reading",
  "signal-position": "execution-assumptions",
  "position-lag": "execution-assumptions",
  "transaction-costs": "execution-assumptions",
  "wrong-backtest-demo": "validation",
  "lookahead-bias-demo": "validation",
  "backtest-report": "research-writing",
  "parameter-scan": "validation",
  "in-sample-out-of-sample": "validation",
  "best-parameter-transfer": "validation",
  "backtest-cannot-predict-future": "research-writing",
  "capstone-research-report": "research-writing",
};

const code = {
  dailyReturn: `def daily_return(previous_price: float, current_price: float) -> float:
    if previous_price <= 0:
        raise ValueError("previous_price must be positive")
    return current_price / previous_price - 1`,
  readCsv: `from pathlib import Path
import pandas as pd

def read_price_csv(path: str | Path) -> pd.DataFrame:
    df = pd.read_csv(path, parse_dates=["date"])
    df = df.sort_values("date").set_index("date")
    return df`,
  ohlcv: `REQUIRED_OHLCV_COLUMNS = {"open", "high", "low", "close", "volume"}

def validate_ohlcv_columns(df: pd.DataFrame) -> None:
    missing = REQUIRED_OHLCV_COLUMNS.difference(df.columns)
    if missing:
        raise ValueError(f"missing OHLCV columns: {sorted(missing)}")`,
  adjusted: `def choose_price_column(df: pd.DataFrame, adjusted: bool = True) -> pd.Series:
    if adjusted and "adj_close" in df.columns:
        return df["adj_close"]
    if "close" not in df.columns:
        raise ValueError("price data must contain close")
    return df["close"]`,
  quality: `def validate_price_data(df: pd.DataFrame) -> dict:
    return {
        "rows": len(df),
        "start": str(df.index.min().date()),
        "end": str(df.index.max().date()),
        "missing_values": int(df.isna().sum().sum()),
        "duplicate_dates": int(df.index.duplicated().sum()),
        "is_monotonic": bool(df.index.is_monotonic_increasing),
        "non_positive_close": int((df["close"] <= 0).sum()) if "close" in df else None,
    }`,
  returns: `def calculate_returns(prices: pd.Series) -> pd.Series:
    returns = prices.astype(float).pct_change()
    return returns.dropna()`,
  compound: `def compound_returns(returns: pd.Series) -> pd.Series:
    clean_returns = returns.dropna().astype(float)
    return (1 + clean_returns).cumprod()`,
  drawdown: `def drawdown_series(equity: pd.Series) -> pd.Series:
    running_max = equity.cummax()
    return equity / running_max - 1

def max_drawdown(equity: pd.Series) -> float:
    return float(drawdown_series(equity).min())`,
  sharpe: `import numpy as np

def sharpe_ratio(returns: pd.Series, risk_free_rate: float = 0.0, periods_per_year: int = 252) -> float:
    clean = returns.dropna().astype(float)
    if clean.empty:
        return float("nan")
    daily_rf = risk_free_rate / periods_per_year
    excess = clean - daily_rf
    volatility = clean.std(ddof=1)
    if volatility == 0 or np.isnan(volatility):
        return float("nan")
    return float(excess.mean() / volatility * np.sqrt(periods_per_year))`,
  positions: `def signals_to_positions(signals: pd.Series, lag: int = 1) -> pd.Series:
    if lag < 0:
        raise ValueError("lag must be non-negative")
    return signals.shift(lag).fillna(0.0)`,
  costs: `def calculate_turnover(positions: pd.Series) -> pd.Series:
    return positions.diff().abs().fillna(positions.abs())

def apply_transaction_costs(returns, positions, commission_bps=0.0, slippage_bps=0.0):
    turnover = calculate_turnover(positions)
    cost_rate = (commission_bps + slippage_bps) / 10_000
    return returns - turnover * cost_rate`,
  buyHold: `def buy_and_hold_signal(prices: pd.Series) -> pd.Series:
    signal = pd.Series(1.0, index=prices.index)
    if not signal.empty:
        signal.iloc[0] = 0.0
    return signal`,
  backtest: `def run_backtest(prices: pd.Series, signals: pd.Series, config: BacktestConfig) -> BacktestResult:
    asset_returns = calculate_returns(prices)
    positions = signals_to_positions(signals, lag=config.signal_lag).reindex(asset_returns.index).fillna(0)
    strategy_returns = asset_returns * positions
    strategy_returns = apply_transaction_costs(
        strategy_returns,
        positions,
        commission_bps=config.commission_bps,
        slippage_bps=config.slippage_bps,
    )
    equity = compound_returns(strategy_returns)
    return BacktestResult.from_series(config, asset_returns, positions, strategy_returns, equity)`,
  movingAverage: `def moving_average_crossover(prices: pd.Series, fast_window: int, slow_window: int) -> pd.Series:
    if fast_window <= 0 or slow_window <= 0:
        raise ValueError("window sizes must be positive")
    if fast_window >= slow_window:
        raise ValueError("fast_window must be smaller than slow_window")
    fast = prices.rolling(fast_window).mean()
    slow = prices.rolling(slow_window).mean()
    return (fast > slow).astype(float).fillna(0.0)`,
  annualized: `def annualized_return(returns: pd.Series, periods_per_year: int = 252) -> float:
    clean = returns.dropna().astype(float)
    if clean.empty:
        return float("nan")
    ending_equity = float((1 + clean).prod())
    return ending_equity ** (periods_per_year / len(clean)) - 1`,
  volatility: `def annualized_volatility(returns: pd.Series, periods_per_year: int = 252) -> float:
    clean = returns.dropna().astype(float)
    if len(clean) < 2:
        return float("nan")
    return float(clean.std(ddof=1) * np.sqrt(periods_per_year))`,
  winLoss: `def win_rate(trade_returns: pd.Series) -> float:
    clean = trade_returns.dropna().astype(float)
    return float((clean > 0).mean()) if not clean.empty else float("nan")

def profit_loss_ratio(trade_returns: pd.Series) -> float:
    wins = trade_returns[trade_returns > 0]
    losses = trade_returns[trade_returns < 0]
    if wins.empty or losses.empty:
        return float("nan")
    return float(wins.mean() / abs(losses.mean()))`,
  weights: `def normalize_weights(weights: pd.Series | pd.DataFrame):
    totals = weights.abs().sum(axis=1)
    return weights.div(totals.replace(0, pd.NA), axis=0).fillna(0.0)`,
  report: `def generate_backtest_report(result: BacktestResult) -> dict:
    return {
        "name": result.config.name,
        "disclaimer": "教育用途，不构成投资建议；历史回测结果不代表未来收益。",
        "metrics": result.metrics,
        "date_range": {
            "start": str(result.equity_curve.index.min().date()),
            "end": str(result.equity_curve.index.max().date()),
        },
    }`,
  momentum: `def momentum_signal(prices: pd.Series, lookback: int) -> pd.Series:
    momentum = prices.astype(float).pct_change(lookback)
    return (momentum > 0).astype(float).fillna(0.0)`,
  meanReversion: `def mean_reversion_signal(prices: pd.Series, window: int, threshold: float) -> pd.Series:
    mean = prices.rolling(window).mean()
    std = prices.rolling(window).std()
    z_score = (prices - mean) / std
    return (z_score < -threshold).astype(float).fillna(0.0)`,
  portfolio: `def equal_weight_portfolio(returns: pd.DataFrame) -> pd.Series:
    return returns.astype(float).mean(axis=1).rename("portfolio_returns")`,
  rotation: `def momentum_rotation_signal(prices: pd.DataFrame, lookback: int, top_n: int = 1) -> pd.DataFrame:
    momentum = prices.astype(float).pct_change(lookback)
    ranks = momentum.rank(axis=1, ascending=False, method="first")
    return (ranks <= top_n).astype(float).fillna(0.0)`,
  scan: `def scan_moving_average_parameters(prices, fast_windows, slow_windows):
    rows = []
    for fast in fast_windows:
        for slow in slow_windows:
            if fast >= slow:
                continue
            signal = moving_average_crossover(prices, fast, slow)
            result = run_backtest(prices, signal)
            rows.append({"fast_window": fast, "slow_window": slow, **result.metrics})
    return pd.DataFrame(rows)`,
  split: `def train_test_split_time_series(data, split_date: str):
    split = pd.Timestamp(split_date)
    return data.loc[data.index <= split], data.loc[data.index > split]`,
  randomStrategies: `def simulate_random_strategies(prices: pd.Series, n_strategies: int, seed: int = 42) -> pd.DataFrame:
    rng = np.random.default_rng(seed)
    rows = []
    for strategy_id in range(n_strategies):
        signal = pd.Series(rng.integers(0, 2, len(prices)), index=prices.index)
        rows.append(run_backtest(prices, signal).metrics | {"strategy_id": strategy_id})
    return pd.DataFrame(rows)`,
  yearly: `def yearly_performance(returns: pd.Series) -> pd.DataFrame:
    rows = []
    for year, group in returns.dropna().groupby(returns.dropna().index.year):
        rows.append({"year": int(year), **performance_summary(group)})
    return pd.DataFrame(rows)`,
  paperLog: `def paper_signal_log(date, symbol: str, signal: float, reason: str) -> dict:
    return {
        "date": str(pd.Timestamp(date).date()),
        "symbol": symbol,
        "signal": float(signal),
        "reason": reason,
        "note": "paper log only; no order is sent",
    }`,
};

const task = (lesson: string, functionName: string, targetFile: string, testFile: string) => `你正在实现 learn-quant-with-codex 的 ${lesson}。

背景：
- 当前课程讲到一个量化入门概念。
- 项目是教育用途，不提供投资建议，不联网，不做实盘交易。

任务：
- 在 ${targetFile} 中实现 ${functionName}。
- 保持输入和输出的索引对齐。
- 对空输入、缺失值或非法参数给出明确行为。

验收：
- 新增或更新 ${testFile}。
- 运行 uv run pytest。
- 用一个极小 DataFrame 或 Series 解释结果。

请先说明实现思路，再修改代码，最后总结这个函数可能被误用的地方。`;

type SupplementalLessonInput = Omit<Lesson, "difficulty" | "duration" | "quiz" | "codexTask" | "skillLine"> & {
  difficulty?: Lesson["difficulty"];
  duration?: string;
  skillLine?: SkillLineId;
  quizQuestion: string;
  correctLabel: string;
  wrongLabels: [string, string];
  quizExplanation: string;
  codexFunction: string;
  targetFile: string;
  testFile: string;
};

function makeLesson(input: SupplementalLessonInput): Lesson {
  return {
    difficulty: input.difficulty ?? "基础",
    duration: input.duration ?? "15 分钟",
    ...input,
    skillLine: input.skillLine ?? lessonSkillOverrides[input.slug] ?? moduleSkillLines[input.moduleId]?.[0] ?? "research-writing",
    quiz: {
      question: input.quizQuestion,
      options: [
        { label: input.correctLabel, value: "correct" },
        { label: input.wrongLabels[0], value: "wrong1" },
        { label: input.wrongLabels[1], value: "wrong2" },
      ],
      correctValue: "correct",
      explanation: input.quizExplanation,
    },
    codexTask: task(input.id + " " + input.title, input.codexFunction, input.targetFile, input.testFile),
  };
}

const lessons: Lesson[] = [
  {
    id: "0.1",
    moduleId: "m0",
    order: 1,
    slug: "project-boundary",
    title: "这门课学什么，不学什么",
    subtitle: "先把边界说清楚：这是学习项目，不是赚钱系统。",
    difficulty: "入门",
    duration: "8 分钟",
    pythonModule: "README.md",
    objectives: ["区分量化研究、回测、paper trading 和实盘交易", "理解为什么课程不会提供投资建议", "知道最终会完成一个学习型研究报告"],
    concepts: ["量化研究", "回测", "paper trading", "实盘交易", "非投资建议"],
    intuition: "量化学习像是在实验室里研究问题。你会写代码、看数据、画图、检查假设，但实验室结果不能直接等同于真实市场里的资金结果。",
    handExample: "如果一个策略在历史数据上从 1.00 涨到 1.20，这只能说明它在这段历史样本里的回测净值上涨了 20%，不能说明未来也会上涨 20%。",
    pythonCode: `PROJECT_BOUNDARY = "education only, not investment advice"`,
    chart: "learning-path",
    chartNote: "学习路径图把课程分成数据、指标、仓位、回测、策略、验证和报告几个阶段。",
    mistakes: ["把回测截图当成收益承诺", "没理解交易成本和执行问题就谈实盘", "只追求策略收益，不学习验证方法"],
    quiz: {
      question: "这门课里的双均线策略应该被理解为什么？",
      options: [
        { label: "学习案例", value: "case" },
        { label: "投资建议", value: "advice" },
        { label: "保证盈利的方法", value: "guarantee" },
      ],
      correctValue: "case",
      explanation: "课程策略只用于学习如何编码、回测和审查假设，不构成投资建议。",
    },
    codexTask: task("0.1 项目边界", "项目风险声明", "README.md", "无需测试"),
    checkpoint: ["能说出本项目不是投资建议", "能解释回测和实盘的区别", "知道课程最终产物是一份学习报告"],
    skillLine: "research-writing",
  },
  {
    id: "0.2",
    moduleId: "m0",
    order: 2,
    slug: "codex-workflow",
    title: "用 Codex 学量化的工作流",
    subtitle: "不要只让 Codex 写代码，要让它解释、实现、测试和反思。",
    difficulty: "入门",
    duration: "10 分钟",
    pythonModule: "quant_learning.metrics",
    objectives: ["掌握 Explain -> Implement -> Test -> Reflect 工作流", "学会给 Codex 明确约束和验收标准", "写出第一个可测试函数"],
    concepts: ["Prompt", "验收标准", "pytest", "边界条件"],
    intuition: "好的 Prompt 像一张小工单：它说清楚背景、目标、输入输出、限制和怎样算完成。这样 Codex 生成的代码更容易被你检查。",
    formula: "daily_return = current_price / previous_price - 1",
    handExample: "100 美元涨到 105 美元，收益率是 105 / 100 - 1 = 0.05，也就是 5%。",
    pythonCode: code.dailyReturn,
    chart: "learning-path",
    chartNote: "这节课的图展示从课程问题到函数、测试、图表和总结的闭环。",
    mistakes: ["Prompt 只写“帮我写个函数”", "没有告诉 Codex 不能联网或不能做投资建议", "没有要求测试"],
    quiz: {
      question: "一个适合课程项目的 Codex Prompt 至少应该包含什么？",
      options: [
        { label: "任务、约束、验收", value: "complete" },
        { label: "只写函数名", value: "name" },
        { label: "只说越快越好", value: "fast" },
      ],
      correctValue: "complete",
      explanation: "任务、约束和验收标准能让实现更可检查。",
    },
    codexTask: task("0.2 Codex 学习工作流", "daily_return", "python/src/quant_learning/metrics.py", "python/tests/test_metrics.py"),
    checkpoint: ["能写出带约束的 Prompt", "知道测试是学习过程的一部分", "能手算一个最简单收益率"],
    skillLine: "research-writing",
  },
  {
    id: "1.1",
    moduleId: "m1",
    order: 101,
    slug: "us-market-and-ticker",
    title: "美股市场和 ticker",
    subtitle: "先理解股票数据里的代码、交易日和指数。",
    difficulty: "入门",
    duration: "12 分钟",
    pythonModule: "quant_learning.data",
    objectives: ["理解 ticker、股票、ETF 和指数", "知道日线数据只覆盖交易日", "读取第一份本地 CSV"],
    concepts: ["ticker", "NYSE", "Nasdaq", "ETF", "S&P 500", "交易日"],
    intuition: "ticker 是市场里用来识别证券的短代码。比如 SPY 不是公司名，而是跟踪 S&P 500 的 ETF 代码。",
    handExample: "如果 CSV 里有 3 个 symbol：AAPL、MSFT、SPY，它们分别代表苹果、微软和一个指数 ETF 学习样例。",
    pythonCode: code.readCsv,
    chart: "price",
    chartNote: "价格曲线展示一只股票在多个交易日里的收盘价变化。",
    mistakes: ["把 ticker 当成公司全名", "以为每一天都有交易数据", "把指数和 ETF 完全混为一谈"],
    quiz: {
      question: "SPY 在课程样例里更接近什么？",
      options: [
        { label: "ETF 代码", value: "etf" },
        { label: "公司全称", value: "company" },
        { label: "交易所名称", value: "exchange" },
      ],
      correctValue: "etf",
      explanation: "SPY 是一个常见 ETF ticker，课程中用它作为基准学习样例。",
    },
    codexTask: task("1.1 美股市场和 ticker", "read_price_csv", "python/src/quant_learning/data.py", "python/tests/test_data.py"),
    checkpoint: ["能解释 ticker 的作用", "知道周末通常没有日线数据", "能读取本地 CSV"],
    skillLine: "data-review",
  },
  {
    id: "1.3",
    moduleId: "m1",
    order: 103,
    slug: "ohlcv",
    title: "OHLCV：一行日线数据",
    subtitle: "Open、High、Low、Close、Volume 是最基础的价格语言。",
    difficulty: "入门",
    duration: "14 分钟",
    pythonModule: "quant_learning.data",
    objectives: ["读懂一行 OHLCV 数据", "检查必要列是否存在", "理解 High、Low 和 Close 的区别"],
    concepts: ["Open", "High", "Low", "Close", "Volume", "日线"],
    intuition: "一行日线数据像是一张当天交易小结：开盘从哪里开始，最高最低到过哪里，最后收在哪里，成交量有多少。",
    handExample: "如果 open=100、high=106、low=98、close=104，说明当天收盘高于开盘，但盘中也曾跌到 98。",
    pythonCode: code.ohlcv,
    chart: "ohlcv",
    chartNote: "简化 OHLC 图帮助你看到同一天里 open、high、low、close 的关系。",
    mistakes: ["把 high 当成最终成交价", "只看 close 忽略 volume", "不检查列名就进入回测"],
    quiz: {
      question: "日线数据里的 Close 表示什么？",
      options: [
        { label: "当天收盘价", value: "close" },
        { label: "当天最高价", value: "high" },
        { label: "当天成交量", value: "volume" },
      ],
      correctValue: "close",
      explanation: "Close 是该交易日最后记录的收盘价格，不是最高价或成交量。",
    },
    codexTask: task("1.3 OHLCV", "validate_ohlcv_columns", "python/src/quant_learning/data.py", "python/tests/test_data.py"),
    checkpoint: ["能读懂一行 OHLCV", "能说出 high 和 close 的区别", "能检查必要列"],
    skillLine: "data-review",
  },
  {
    id: "1.4",
    moduleId: "m1",
    order: 104,
    slug: "close-vs-adjusted-close",
    title: "Close 和 Adjusted Close",
    subtitle: "拆股和分红会让普通收盘价在长期回测中误导你。",
    difficulty: "基础",
    duration: "15 分钟",
    pythonModule: "quant_learning.data",
    objectives: ["理解 close 和 adjusted close 的区别", "知道拆股会改变历史价格表现", "选择合适价格列计算收益"],
    concepts: ["Close", "Adjusted Close", "split", "dividend", "复权"],
    intuition: "如果一家公司 1 股拆成 2 股，普通 close 可能突然减半。但投资者的经济价值不一定减半，所以长期收益通常需要看复权价格。",
    handExample: "某股票 close 从 105 变成 53，看起来跌了接近一半；但 adj_close 从 105 到 106，说明这更像拆股调整，而不是一天暴跌。",
    pythonCode: code.adjusted,
    chart: "adjusted-close",
    chartNote: "Close 曲线出现断崖，Adjusted Close 曲线保持连续，帮助解释复权价格的意义。",
    mistakes: ["长期回测直接使用未复权 close", "看到价格减半就判断公司价值减半", "没有记录自己选择了哪一列价格"],
    quiz: {
      question: "长期回测通常优先使用哪类价格？",
      options: [
        { label: "复权价格", value: "adjusted" },
        { label: "成交量", value: "volume" },
        { label: "当天最高价", value: "high" },
      ],
      correctValue: "adjusted",
      explanation: "复权价格能更好处理拆股和分红对历史收益的影响。",
    },
    codexTask: task("1.4 Close 和 Adjusted Close", "choose_price_column", "python/src/quant_learning/data.py", "python/tests/test_data.py"),
    checkpoint: ["能解释复权价格", "知道 close 曲线可能有拆股断点", "能在代码中选择价格列"],
    skillLine: "data-review",
  },
  {
    id: "1.5",
    moduleId: "m1",
    order: 105,
    slug: "data-quality",
    title: "数据清洗和质量检查",
    subtitle: "回测前先检查数据，否则后面的结果都不可靠。",
    difficulty: "基础",
    duration: "16 分钟",
    pythonModule: "quant_learning.data",
    objectives: ["识别缺失值、重复日期和异常价格", "输出数据质量报告", "理解为什么不能盲目修复数据"],
    concepts: ["missing data", "duplicate index", "outlier", "data quality"],
    intuition: "数据质量检查像出发前看地图和油量。你不一定马上修车，但至少要知道车哪里可能有问题。",
    handExample: "如果同一天出现两行价格，回测器可能计算两次收益；如果 close 为 0，收益率会变成无意义的巨大数字。",
    pythonCode: code.quality,
    chart: "data-quality",
    chartNote: "数据质量图把缺失值、重复日期和异常价格标出来，避免问题藏在表格里。",
    mistakes: ["下载数据后直接回测", "静默删除异常值但不记录", "把所有缺失值都用前一天价格填充"],
    quiz: {
      question: "回测前发现重复日期，最合理的第一步是什么？",
      options: [
        { label: "记录并调查原因", value: "inspect" },
        { label: "直接忽略", value: "ignore" },
        { label: "把价格乘以 2", value: "double" },
      ],
      correctValue: "inspect",
      explanation: "重复日期会影响收益路径，应该先记录并调查，而不是静默忽略。",
    },
    codexTask: task("1.5 数据质量检查", "validate_price_data", "python/src/quant_learning/data.py", "python/tests/test_data.py"),
    checkpoint: ["能列出 4 个数据检查项", "能生成质量报告", "知道不要静默修复严重问题"],
    skillLine: "data-review",
  },
  {
    id: "2.1",
    moduleId: "m2",
    order: 201,
    slug: "returns",
    title: "收益率：价格变化的百分比",
    subtitle: "10 美元上涨不总是同一件事，百分比才方便比较。",
    difficulty: "入门",
    duration: "14 分钟",
    pythonModule: "quant_learning.metrics",
    objectives: ["理解价格变化和收益率的区别", "计算日收益率序列", "处理第一天没有收益的问题"],
    concepts: ["return", "pct_change", "daily return", "索引对齐"],
    intuition: "100 涨到 110 和 1000 涨到 1010 都涨了 10 美元，但前者是 10%，后者只有 1%。收益率让不同价格水平可以比较。",
    formula: "return_t = price_t / price_{t-1} - 1",
    handExample: "价格从 100 到 102，收益率是 2%；从 102 到 101，收益率是 -0.98%。",
    pythonCode: code.returns,
    chart: "returns",
    chartNote: "同一张图同时展示价格曲线和日收益率柱状图，强调价格和收益不是同一种信息。",
    mistakes: ["用绝对涨跌代替收益率", "忘记第一天没有上一日价格", "把 NaN 当成 0 之前不说明原因"],
    quiz: {
      question: "股票 A 从 10 涨到 11，股票 B 从 100 涨到 101，谁的收益率更高？",
      options: [
        { label: "股票 A", value: "a" },
        { label: "股票 B", value: "b" },
        { label: "一样高", value: "same" },
      ],
      correctValue: "a",
      explanation: "A 上涨 10%，B 上涨 1%。绝对涨幅相同，收益率不同。",
    },
    codexTask: task("2.1 收益率", "calculate_returns", "python/src/quant_learning/metrics.py", "python/tests/test_metrics.py"),
    checkpoint: ["能手算简单收益率", "能解释第一天为什么没有收益", "能用 pandas 计算收益序列"],
    skillLine: "return-path",
  },
  {
    id: "2.3",
    moduleId: "m2",
    order: 203,
    slug: "compound-equity",
    title: "复利和净值曲线",
    subtitle: "策略表现不是把每日收益简单相加，而是沿路径累乘。",
    difficulty: "基础",
    duration: "15 分钟",
    pythonModule: "quant_learning.metrics",
    objectives: ["理解复利累乘", "从收益率生成净值曲线", "读懂 equity curve"],
    concepts: ["compound return", "equity curve", "cumprod"],
    intuition: "净值曲线从 1.00 开始，记录每一天你的学习型组合相对初始资金变成了多少。它显示路径，而不是只显示终点。",
    formula: "equity_t = product(1 + return_i)",
    handExample: "第一天 +10%，第二天 -10%，净值是 1.1 * 0.9 = 0.99，不是回到 1.00。",
    pythonCode: code.compound,
    chart: "equity",
    chartNote: "净值曲线让你看到策略经历了哪些上涨、回落和恢复。",
    mistakes: ["把每日收益直接相加当最终收益", "只看终点不看路径", "忘记负收益后的恢复需要更大涨幅"],
    quiz: {
      question: "+10% 后再 -10%，最终净值是多少？",
      options: [
        { label: "0.99", value: "099" },
        { label: "1.00", value: "100" },
        { label: "1.10", value: "110" },
      ],
      correctValue: "099",
      explanation: "1.1 * 0.9 = 0.99，复利路径不是简单加减。",
    },
    codexTask: task("2.3 复利和净值曲线", "compound_returns", "python/src/quant_learning/metrics.py", "python/tests/test_metrics.py"),
    checkpoint: ["能解释 equity curve", "知道复利不是简单相加", "能从收益率生成净值"],
    skillLine: "return-path",
  },
  {
    id: "3.2",
    moduleId: "m3",
    order: 302,
    slug: "max-drawdown",
    title: "最大回撤",
    subtitle: "收益曲线从历史高点跌下来多少，往往比最终收益更刺眼。",
    difficulty: "基础",
    duration: "16 分钟",
    pythonModule: "quant_learning.metrics",
    objectives: ["理解 running max", "计算回撤序列", "找到最大回撤"],
    concepts: ["drawdown", "running max", "max drawdown"],
    intuition: "最大回撤描述从高点到低点的最坏下跌。它回答的是：如果你在最难受的位置持有，会经历多大的账面回落。",
    formula: "drawdown_t = equity_t / running_max_t - 1",
    handExample: "净值从 1.20 跌到 0.96，回撤是 0.96 / 1.20 - 1 = -20%。",
    pythonCode: code.drawdown,
    chart: "drawdown",
    chartNote: "上图看净值，下图看回撤。回撤越向下，代表离历史高点越远。",
    mistakes: ["只看最终收益，不看中途下跌", "把单日亏损当成最大回撤", "忽略恢复到新高需要时间"],
    quiz: {
      question: "净值从历史高点 1.20 跌到 1.02，回撤约为多少？",
      options: [
        { label: "-15%", value: "15" },
        { label: "-2%", value: "2" },
        { label: "+15%", value: "plus" },
      ],
      correctValue: "15",
      explanation: "1.02 / 1.20 - 1 = -0.15，也就是 -15%。",
    },
    codexTask: task("3.2 最大回撤", "drawdown_series 和 max_drawdown", "python/src/quant_learning/metrics.py", "python/tests/test_metrics.py"),
    checkpoint: ["能计算回撤", "能读懂回撤曲线", "知道最大回撤不是单日亏损"],
    skillLine: "risk-reading",
  },
  {
    id: "3.3",
    moduleId: "m3",
    order: 303,
    slug: "sharpe-ratio",
    title: "夏普比率",
    subtitle: "收益高不等于策略好，还要看承担了多少波动。",
    difficulty: "基础",
    duration: "18 分钟",
    pythonModule: "quant_learning.metrics",
    objectives: ["理解风险调整后收益", "知道夏普比率依赖收益均值和波动率", "处理零波动边界"],
    concepts: ["Sharpe ratio", "excess return", "risk-free rate", "annualization"],
    intuition: "夏普比率尝试回答：承担这些波动，换来的平均收益是否值得？它不是策略排名答案，只是把收益和波动放进同一个问题里。",
    formula: "sharpe = mean(excess_returns) / std(returns) * sqrt(252)",
    handExample: "策略 A 日均收益 0.08%、日波动 1%，策略 B 日均收益 0.05%、日波动 0.3%。A 收益更高，但 B 的风险调整后收益可能更好。",
    pythonCode: code.sharpe,
    chart: "metrics",
    chartNote: "指标卡片并排展示收益、波动率、回撤和夏普，提醒你不要只看单一数字。",
    mistakes: ["收益高就认为策略好", "夏普高就忽略最大回撤", "零波动时强行计算夏普"],
    quiz: {
      question: "夏普比率主要想把收益和什么放在一起看？",
      options: [
        { label: "波动率", value: "volatility" },
        { label: "ticker 长度", value: "ticker" },
        { label: "未来收益保证", value: "guarantee" },
      ],
      correctValue: "volatility",
      explanation: "夏普比率用平均超额收益除以收益波动率，再做年化。",
    },
    codexTask: task("3.3 夏普比率", "sharpe_ratio", "python/src/quant_learning/metrics.py", "python/tests/test_metrics.py"),
    checkpoint: ["能解释夏普比率直觉", "知道收益和波动要一起看", "知道单一指标不能评价完整策略"],
    skillLine: "risk-reading",
  },
  {
    id: "4.1",
    moduleId: "m4",
    order: 401,
    slug: "signal-position",
    title: "Signal 是想法，不是收益",
    subtitle: "信号只是策略想法，还没有变成持仓、成交和收益。",
    difficulty: "基础",
    duration: "17 分钟",
    pythonModule: "quant_learning.positions",
    objectives: ["理解 signal 是策略规则输出", "用 0/1 序列表达学习信号", "知道 signal 不能直接乘收益"],
    concepts: ["signal", "entry", "exit", "trading rule", "learning signal"],
    intuition: "Signal 是策略说“我想买、想卖或观望”的想法。它还没有说明哪一天真的持仓，也没有说明买多少，更不能直接等于收益。",
    formula: "signal_t = 1 if condition_t else 0",
    handExample: "如果 1 月 3 日收盘价高于 20 日均线，signal 可以是 1；这只表示收盘后产生了买入想法，不表示 1 月 3 日已经吃到当天收益。",
    pythonCode: `def price_above_average_signal(prices: pd.Series, average: pd.Series) -> pd.Series:
    return (prices > average).astype(float).fillna(0.0)`,
    chart: "position",
    chartNote: "信号标记图先只展示策略想法出现在哪些日期，下一课再把它转换为 position。",
    mistakes: ["把 signal 当作成交记录", "把 signal 直接乘以当天收益", "没有说明信号在什么时间点产生"],
    quiz: {
      question: "Signal 在课程项目里首先代表什么？",
      options: [
        { label: "策略规则输出的想法", value: "idea" },
        { label: "已经成交的仓位", value: "filled" },
        { label: "未来收益保证", value: "guarantee" },
      ],
      correctValue: "idea",
      explanation: "Signal 是策略想法，必须再经过 position、lag 和成本处理才进入回测收益。",
    },
    codexTask: task("4.1 Signal 是想法", "一个 0/1 signal 示例和索引对齐测试", "python/src/quant_learning/positions.py", "python/tests/test_positions.py"),
    checkpoint: ["能解释 signal 是策略想法", "知道 signal 不是收益", "能说明信号产生的时间点"],
    skillLine: "execution-assumptions",
  },
  {
    id: "4.2",
    moduleId: "m4",
    order: 402,
    slug: "position-lag",
    title: "Position 才是持仓",
    subtitle: "仓位决定你哪一天真的承担收益，日线回测通常要让 signal 滞后一日。",
    difficulty: "基础",
    duration: "17 分钟",
    pythonModule: "quant_learning.positions",
    objectives: ["把 signal 转换为 position", "理解 shift、lag 和索引对齐", "避免当天收盘信号当天成交的前视偏差"],
    concepts: ["position", "shift", "lag", "look-ahead bias"],
    intuition: "当天收盘后你才知道收盘价。如果你用这个收盘价产生信号，就不能再假设自己已经按同一个收盘价提前成交。Position 是回测真正用来承担收益的序列。",
    formula: "position_t = signal_{t-1}",
    handExample: "1 月 3 日收盘后出现买入信号，更保守的日线回测会从 1 月 4 日开始持仓。",
    pythonCode: code.positions,
    chart: "position",
    chartNote: "图里 signal 比 position 早一天变化，展示滞后持仓如何减少最明显的 look-ahead bias。",
    mistakes: ["当天信号当天收盘成交", "把 signal 直接乘以当天收益", "没有检查 signal、position 和 returns 的索引是否对齐"],
    quiz: {
      question: "用当天收盘价生成信号，又按当天收盘价成交，最大风险是什么？",
      options: [
        { label: "look-ahead bias", value: "bias" },
        { label: "成交量太大", value: "volume" },
        { label: "ticker 写错", value: "ticker" },
      ],
      correctValue: "bias",
      explanation: "你使用了现实中同一时刻无法同时知道并成交的信息。",
    },
    codexTask: task("4.2 Position 才是持仓", "signals_to_positions", "python/src/quant_learning/positions.py", "python/tests/test_positions.py"),
    checkpoint: ["能区分 signal 和 position", "知道 position 默认滞后一日", "能指出 look-ahead bias"],
    skillLine: "execution-assumptions",
  },
  {
    id: "4.3",
    moduleId: "m4",
    order: 403,
    slug: "transaction-costs",
    title: "手续费和滑点",
    subtitle: "交易越频繁，越需要认真看成本。",
    difficulty: "基础",
    duration: "16 分钟",
    pythonModule: "quant_learning.costs",
    objectives: ["理解 commission、slippage 和 bps", "用仓位变化估算换手", "比较有成本和无成本净值"],
    concepts: ["commission", "slippage", "basis points", "turnover"],
    intuition: "回测里每次换仓都像过收费站。一次费用很小，但高换手策略会反复经过，最终吞掉很多收益。",
    formula: "cost = turnover * (commission_bps + slippage_bps) / 10000",
    handExample: "如果换手为 1，手续费和滑点合计 10 bps，则成本是 0.001，也就是 0.1%。",
    pythonCode: code.costs,
    chart: "costs",
    chartNote: "成本对比图显示无成本曲线通常更好看，但更不现实。",
    mistakes: ["忽略交易成本", "以为 bps 是百分比本身", "没有把成本和换手联系起来"],
    quiz: {
      question: "10 bps 等于多少？",
      options: [
        { label: "0.1%", value: "01" },
        { label: "10%", value: "10" },
        { label: "1%", value: "1" },
      ],
      correctValue: "01",
      explanation: "1 bps = 0.01%，所以 10 bps = 0.1%。",
    },
    codexTask: task("4.3 手续费和滑点", "calculate_turnover 和 apply_transaction_costs", "python/src/quant_learning/costs.py", "python/tests/test_costs.py"),
    checkpoint: ["能解释 bps", "能计算换手成本", "知道高换手策略对成本敏感"],
    skillLine: "execution-assumptions",
  },
  {
    id: "5.1",
    moduleId: "m5",
    order: 501,
    slug: "buy-and-hold",
    title: "Buy and Hold 基准策略",
    subtitle: "先有基准，才知道一个策略是否值得继续研究。",
    difficulty: "基础",
    duration: "14 分钟",
    pythonModule: "quant_learning.strategies",
    objectives: ["理解 benchmark", "实现 buy and hold signal", "用它作为策略比较起点"],
    concepts: ["benchmark", "buy and hold", "baseline"],
    intuition: "如果一个复杂策略连简单买入并持有都比不过，那它至少需要解释为什么还值得研究，比如回撤更小或成本更低。",
    handExample: "从第二个交易日起一直持仓为 1，就能得到最简单的持有型收益路径。",
    pythonCode: code.buyHold,
    chart: "backtest",
    chartNote: "基准图展示 buy and hold 的净值和回撤，后续策略都要和它比较。",
    mistakes: ["没有基准就评价策略", "只和现金比较", "忽略基准的风险指标"],
    quiz: {
      question: "为什么需要 benchmark？",
      options: [
        { label: "提供比较基准", value: "compare" },
        { label: "保证策略赚钱", value: "guarantee" },
        { label: "替代数据质量检查", value: "data" },
      ],
      correctValue: "compare",
      explanation: "benchmark 帮助判断策略表现是否相对简单选择有意义。",
    },
    codexTask: task("5.1 Buy and Hold", "buy_and_hold_signal", "python/src/quant_learning/strategies.py", "python/tests/test_strategies.py"),
    checkpoint: ["能解释 benchmark", "能实现 buy and hold signal", "知道策略比较不能脱离基准"],
    skillLine: "return-path",
  },
  {
    id: "5.2",
    moduleId: "m5",
    order: 502,
    slug: "minimal-backtester",
    title: "最小可用回测器",
    subtitle: "把价格、信号、仓位、成本、净值和指标串起来。",
    difficulty: "基础",
    duration: "20 分钟",
    pythonModule: "quant_learning.backtest",
    objectives: ["理解回测流程", "实现 BacktestResult", "默认避免 look-ahead bias"],
    concepts: ["asset returns", "strategy returns", "equity curve", "BacktestResult"],
    intuition: "回测器不是神秘工具，它只是稳定地执行一套流程：价格变收益，信号变仓位，仓位乘收益，扣成本，再计算净值和指标。",
    formula: "strategy_return_t = asset_return_t * position_t - cost_t",
    handExample: "如果某天资产收益是 2%，position 是 1，成本是 0.1%，策略收益就是 1.9%。如果 position 是 0，策略不承担这天价格变化。",
    pythonCode: code.backtest,
    chart: "backtest",
    chartNote: "回测图把净值、回撤和指标卡片放在一起，避免只看收益。",
    mistakes: ["把信号直接乘当天收益", "只保存最终收益", "没有测试成本和滞后逻辑"],
    quiz: {
      question: "最小回测器里 position 的作用是什么？",
      options: [
        { label: "决定是否承担当天资产收益", value: "exposure" },
        { label: "替代价格数据", value: "price" },
        { label: "保证没有亏损", value: "safe" },
      ],
      correctValue: "exposure",
      explanation: "position 决定策略在某一天是否暴露于资产收益。",
    },
    codexTask: task("5.2 最小可用回测器", "run_backtest 和 BacktestResult", "python/src/quant_learning/backtest.py", "python/tests/test_backtest.py"),
    checkpoint: ["能说出回测 5 个步骤", "能解释 asset returns 和 strategy returns", "知道默认滞后仓位的重要性"],
    skillLine: "execution-assumptions",
  },
  {
    id: "6.1",
    moduleId: "m6",
    order: 601,
    slug: "moving-average-crossover",
    title: "双均线策略",
    subtitle: "第一种趋势跟随学习案例：快线在慢线上方时持仓。",
    difficulty: "基础",
    duration: "18 分钟",
    pythonModule: "quant_learning.strategies",
    objectives: ["理解 moving average", "实现 fast/slow crossover signal", "知道参数越调越好可能是过拟合"],
    concepts: ["moving average", "fast window", "slow window", "crossover", "trend following"],
    intuition: "移动平均线会把价格噪声平滑掉。快线更敏感，慢线更稳定。快线高于慢线时，策略把它理解为趋势向上学习信号。",
    formula: "signal_t = 1 if MA_fast_t > MA_slow_t else 0",
    handExample: "如果 5 日均线是 108，20 日均线是 104，双均线信号为 1；如果快线低于慢线，信号为 0。",
    pythonCode: code.movingAverage,
    chart: "moving-average",
    chartNote: "图中价格、快线、慢线和 signal 一起出现，帮助理解信号如何从价格派生。",
    mistakes: ["fast_window 大于 slow_window", "调参直到历史最好就停止", "忘记 signal 到 position 需要滞后"],
    quiz: {
      question: "双均线策略里 fast_window 应该通常如何比较 slow_window？",
      options: [
        { label: "更短", value: "shorter" },
        { label: "更长", value: "longer" },
        { label: "必须相等", value: "equal" },
      ],
      correctValue: "shorter",
      explanation: "快线窗口更短，才能更快反映价格变化。",
    },
    codexTask: task("6.1 双均线策略", "moving_average_crossover", "python/src/quant_learning/strategies.py", "python/tests/test_strategies.py"),
    checkpoint: ["能解释快慢均线", "能实现双均线 signal", "知道历史最优参数不代表未来有效"],
    skillLine: "execution-assumptions",
  },
];

lessons.push(
  makeLesson({
    id: "0.3",
    moduleId: "m0",
    order: 3,
    slug: "first-tested-function",
    title: "第一个测试驱动的小函数",
    subtitle: "用一个很小的收益率函数理解“实现”和“验证”的关系。",
    pythonModule: "quant_learning.metrics",
    objectives: ["把手算收益率变成函数", "写出最小 pytest", "知道测试不是形式，而是防止概念跑偏"],
    concepts: ["unit test", "expected value", "edge case"],
    intuition: "初学量化时，最危险的不是公式复杂，而是一个很小的函数算错后被后面的策略反复放大。先测试小函数，是为了让后面的回测更可信。",
    formula: "daily_return(100, 105) = 0.05",
    handExample: "如果函数把 100 到 105 算成 5，而不是 0.05，后面所有年化、净值和夏普都会错。",
    pythonCode: code.dailyReturn,
    chart: "learning-path",
    chartNote: "这张路径图强调：课程中的每个概念都会进入实现和测试。",
    mistakes: ["只看函数能运行，不检查数值", "测试只覆盖一个正常输入", "没有测试非法价格"],
    checkpoint: ["能写一个 pytest", "知道收益率单位是小数", "能解释为什么先测小函数"],
    quizQuestion: "为什么课程从很小的函数开始测试？",
    correctLabel: "小错误会被后续回测放大",
    wrongLabels: ["为了让代码更长", "为了替代课程解释"],
    quizExplanation: "收益率、净值和指标环环相扣，小函数错误会传导到后续结果。",
    codexFunction: "daily_return 和对应 pytest",
    targetFile: "python/src/quant_learning/metrics.py",
    testFile: "python/tests/test_metrics.py",
  }),
  makeLesson({
    id: "1.2",
    moduleId: "m1",
    order: 102,
    slug: "trading-days-and-date-index",
    title: "交易日和日期索引",
    subtitle: "日线数据不是每天都有，日期索引必须按时间顺序工作。",
    pythonModule: "quant_learning.data",
    objectives: ["理解交易日缺口", "使用 DatetimeIndex", "检查日期是否递增"],
    concepts: ["trading day", "DatetimeIndex", "sort_values", "monotonic index"],
    intuition: "股票市场通常周末不交易，所以价格序列天然有日期缺口。缺口不是错误，但重复日期、乱序日期和非时间索引通常会让回测结果变得不可信。",
    handExample: "1 月 5 日后直接到 1 月 8 日，通常只是周末；但两个 1 月 8 日就需要调查。",
    pythonCode: code.readCsv,
    chart: "price",
    chartNote: "价格点只出现在交易日。图上的日期间隔提醒你不要把日历日和交易日混为一谈。",
    mistakes: ["随机打乱时间序列", "把周末缺口当作缺失价格", "没有按日期排序就计算收益率"],
    checkpoint: ["能解释交易日缺口", "能使用 DatetimeIndex", "知道时间序列不能随机打乱"],
    quizQuestion: "日线数据中没有周六价格，最常见原因是什么？",
    correctLabel: "市场通常不交易",
    wrongLabels: ["数据一定坏了", "股票退市了"],
    quizExplanation: "美股日线通常只记录交易日，周末缺口本身不是错误。",
    codexFunction: "read_price_csv 日期处理",
    targetFile: "python/src/quant_learning/data.py",
    testFile: "python/tests/test_data.py",
  }),
  makeLesson({
    id: "2.2",
    moduleId: "m2",
    order: 202,
    slug: "daily-return-series",
    title: "日收益率序列",
    subtitle: "收益率不是一个数，而是一条和日期对齐的路径。",
    pythonModule: "quant_learning.metrics",
    objectives: ["理解首日 NaN", "保持收益率索引对齐", "知道收益序列服务净值和指标"],
    concepts: ["daily returns", "NaN", "index alignment", "pct_change"],
    intuition: "一条收益率序列像每天的成绩单。第一天没有上一天可比，所以不能凭空产生收益。",
    formula: "returns = prices.pct_change().dropna()",
    handExample: "价格为 100、102、101 时，收益率序列只有两个值：2% 和 -0.98%。",
    pythonCode: code.returns,
    chart: "returns",
    chartNote: "柱状图展示每一天的收益率，有正有负，比单纯价格线更能显示短期波动。",
    mistakes: ["强行给第一天填 0 但不说明", "收益和价格索引错位", "把收益率序列当成交易记录"],
    checkpoint: ["能解释首日 NaN", "能保持索引对齐", "能从价格得到日收益序列"],
    quizQuestion: "为什么第一天通常没有收益率？",
    correctLabel: "没有上一日价格可比",
    wrongLabels: ["第一天一定亏损", "第一天成交量为零"],
    quizExplanation: "收益率需要两个价格点，第一天没有前一个价格。",
    codexFunction: "calculate_returns 首日处理",
    targetFile: "python/src/quant_learning/metrics.py",
    testFile: "python/tests/test_metrics.py",
  }),
  makeLesson({
    id: "2.4",
    moduleId: "m2",
    order: 204,
    slug: "annualized-return",
    title: "年化收益率",
    subtitle: "把不同长度的样本放到相近尺度上比较，但短样本会很容易误导。",
    pythonModule: "quant_learning.metrics",
    objectives: ["理解 252 个交易日近似", "计算年化收益", "识别短期年化的误导性"],
    concepts: ["annualized return", "periods_per_year", "sample length"],
    intuition: "年化收益像把一段跑步速度换算成全年速度。它方便比较，但如果你只跑了 10 秒，就不能说自己全年都能保持这个速度。",
    formula: "annual_return = ending_equity ** (252 / n_days) - 1",
    handExample: "5 天上涨 2% 年化后可能很高，但这不代表未来一年能复制这 5 天。",
    pythonCode: code.annualized,
    chart: "annualized",
    chartNote: "净值曲线越短，年化数字越容易被个别涨跌放大。",
    mistakes: ["用几天收益推断全年收益", "忘记说明 periods_per_year", "负净值或空序列仍强行年化"],
    checkpoint: ["能写年化收益公式", "知道 252 是近似", "能说明短期年化风险"],
    quizQuestion: "短样本年化收益最主要的问题是什么？",
    correctLabel: "容易被少数日期放大",
    wrongLabels: ["一定更准确", "不需要净值"],
    quizExplanation: "样本越短，年化越容易把短期偶然波动放大。",
    codexFunction: "annualized_return",
    targetFile: "python/src/quant_learning/metrics.py",
    testFile: "python/tests/test_metrics.py",
  }),
  makeLesson({
    id: "2.5",
    moduleId: "m2",
    order: 205,
    slug: "returns-summary",
    title: "收益率小结",
    subtitle: "把价格、收益率和净值曲线连成一条完整数据链。",
    pythonModule: "quant_learning.metrics",
    objectives: ["串联价格、收益和净值", "生成收益摘要", "为风险指标做准备"],
    concepts: ["price path", "return path", "equity path"],
    intuition: "价格告诉你市场怎么走，收益率告诉你每一步变化，净值曲线告诉你这些变化累积成什么结果。",
    handExample: "同样最终涨到 110，一条平稳上涨路径和一条先跌 30% 再反弹的路径，体验完全不同。",
    pythonCode: `${code.returns}\n\n${code.compound}`,
    chart: "equity",
    chartNote: "这节课把价格、收益和净值作为一个整体观察。",
    mistakes: ["只保留最终收益", "不保存中间收益序列", "忽略路径差异"],
    checkpoint: ["能从价格到收益再到净值", "知道路径比终点更重要", "准备进入风险指标"],
    quizQuestion: "为什么净值曲线比单个总收益更有信息量？",
    correctLabel: "它显示收益路径",
    wrongLabels: ["它保证未来收益", "它不需要价格"],
    quizExplanation: "净值曲线展示过程中的上涨、回落和恢复。",
    codexFunction: "performance_summary 的收益部分",
    targetFile: "python/src/quant_learning/metrics.py",
    testFile: "python/tests/test_metrics.py",
  }),
);

lessons.push(
  makeLesson({
    id: "8.1",
    moduleId: "m8",
    order: 801,
    slug: "parameter-scan",
    title: "参数扫描",
    subtitle: "遍历参数可以观察敏感性，也会诱发挑历史最好看的结果。",
    pythonModule: "quant_learning.experiments",
    objectives: ["扫描 fast/slow 均线参数", "跳过非法组合", "阅读参数结果表"],
    concepts: ["grid search", "parameter scan", "sensitivity"],
    intuition: "参数扫描像调收音机。你能找到历史样本里声音最清楚的位置，但不代表未来也一直清楚。",
    formula: "for fast in fast_windows: for slow in slow_windows",
    handExample: "fast=5、slow=20 和 fast=20、slow=100 可能表现不同，关键是看结果是否稳定，而不是只挑最高值。",
    pythonCode: code.scan,
    chart: "parameter-scan",
    chartNote: "参数图同时展示历史指标和样本外表现，提醒你不要只看样本内最优。",
    mistakes: ["fast >= slow 也参与比较", "只挑最高夏普", "没有记录扫描范围"],
    checkpoint: ["能运行参数扫描", "知道跳过非法组合", "能解释参数敏感性"],
    quizQuestion: "参数扫描时为什么要跳过 fast >= slow？",
    correctLabel: "快线不应慢于慢线",
    wrongLabels: ["为了让收益更高", "因为不能画图"],
    quizExplanation: "双均线定义里 fast_window 应小于 slow_window。",
    codexFunction: "scan_moving_average_parameters",
    targetFile: "python/src/quant_learning/experiments.py",
    testFile: "python/tests/test_experiments.py",
  }),
  makeLesson({
    id: "8.2",
    moduleId: "m8",
    order: 802,
    slug: "in-sample-out-of-sample",
    title: "样本内和样本外",
    subtitle: "先调参，再用未参与调参的历史区间做更严格验证。",
    pythonModule: "quant_learning.experiments",
    objectives: ["按日期切分数据", "区分 train/test", "避免随机打乱时间序列"],
    concepts: ["in-sample", "out-of-sample", "time series split"],
    intuition: "样本内像练习题，样本外像你还没看过的模拟考试。它仍然是历史，不是未来，但比只看练习题更严格。",
    formula: "train = data[index <= split_date], test = data[index > split_date]",
    handExample: "用 2020-2022 调参数，再用 2023 检查表现，比在 2020-2023 全部数据上调参更严谨。",
    pythonCode: code.split,
    chart: "out-of-sample",
    chartNote: "图表把样本内和样本外结果放在一起，观察参数是否迁移。",
    mistakes: ["随机打乱时间序列", "全样本调参后宣称样本外有效", "样本外表现差就继续调样本外"],
    checkpoint: ["能按日期切分", "知道不能随机打乱", "能解释样本外的意义"],
    quizQuestion: "时间序列样本切分为什么不应随机打乱？",
    correctLabel: "会破坏时间顺序",
    wrongLabels: ["会让图表变蓝", "会减少文件数量"],
    quizExplanation: "未来数据不能参与过去决策，时间顺序必须保留。",
    codexFunction: "train_test_split_time_series",
    targetFile: "python/src/quant_learning/experiments.py",
    testFile: "python/tests/test_experiments.py",
  }),
  makeLesson({
    id: "8.3",
    moduleId: "m8",
    order: 803,
    slug: "best-parameter-transfer",
    title: "最优参数迁移测试",
    subtitle: "样本内最优参数到了样本外，常常没有想象中稳定。",
    pythonModule: "quant_learning.experiments",
    objectives: ["选择样本内最优参数", "在样本外复测", "解释迁移失败"],
    concepts: ["best parameter", "transfer", "validation", "overfitting"],
    intuition: "如果参数只是在历史噪声上碰巧最优，换一段时间后它可能立刻失效。迁移测试就是把样本内挑出来的参数拿到另一段历史里复查，观察它是否只是过拟合。",
    handExample: "fast=20/slow=50 在样本内夏普最高，但样本外净值低于 buy and hold，这说明历史最优不稳定。",
    pythonCode: `def evaluate_in_sample_out_of_sample(prices, params, split_date):\n    train, test = train_test_split_time_series(prices, split_date)\n    return {\n        "in_sample": run_backtest(train, moving_average_crossover(train, **params)).metrics,\n        "out_of_sample": run_backtest(test, moving_average_crossover(test, **params)).metrics,\n    }`,
    chart: "out-of-sample",
    chartNote: "样本内和样本外曲线分开观察，避免一条全样本曲线掩盖问题。",
    mistakes: ["样本外差就重新挑样本外参数", "只报告样本内最优", "忽略参数稳定性"],
    checkpoint: ["能验证最优参数迁移", "能解释样本外变差", "知道这仍不是未来保证"],
    quizQuestion: "样本内最优参数样本外变差说明什么？",
    correctLabel: "可能不稳定或过拟合",
    wrongLabels: ["未来必定亏损", "代码一定无法运行"],
    quizExplanation: "样本外变差是警告信号，但需要结合更多分析。",
    codexFunction: "evaluate_in_sample_out_of_sample",
    targetFile: "python/src/quant_learning/experiments.py",
    testFile: "python/tests/test_experiments.py",
  }),
  makeLesson({
    id: "8.4",
    moduleId: "m8",
    order: 804,
    slug: "random-strategy-winners",
    title: "随机策略也会有赢家",
    subtitle: "尝试次数越多，越容易在历史里挑到偶然表现好的曲线。",
    pythonModule: "quant_learning.experiments",
    objectives: ["模拟随机信号", "观察多重测试风险", "识别挑最好截图的问题"],
    concepts: ["random strategy", "multiple testing", "data snooping"],
    intuition: "如果你扔 1000 次硬币，总能找到一段看起来很有规律的结果。市场回测里也有类似风险。",
    handExample: "生成 100 条随机 0/1 信号，总会有几条在短样本里表现很好，但它们没有真实交易逻辑。",
    pythonCode: code.randomStrategies,
    chart: "parameter-scan",
    chartNote: "随机策略云图强调：最好看的历史曲线不一定代表真实规律。",
    mistakes: ["只展示随机策略中最好的一条", "把多次尝试当成一次实验", "不记录尝试次数"],
    checkpoint: ["能模拟随机策略", "知道多重测试风险", "能识别挑截图问题"],
    quizQuestion: "为什么随机策略也可能有历史赢家？",
    correctLabel: "尝试次数多会产生偶然好结果",
    wrongLabels: ["随机信号知道未来", "随机策略没有风险"],
    quizExplanation: "多重测试会让偶然表现好的结果出现概率上升。",
    codexFunction: "simulate_random_strategies",
    targetFile: "python/src/quant_learning/experiments.py",
    testFile: "python/tests/test_experiments.py",
  }),
  makeLesson({
    id: "8.5",
    moduleId: "m8",
    order: 805,
    slug: "yearly-performance",
    title: "分年度表现",
    subtitle: "同一策略在不同市场环境中的表现可能完全不同。",
    pythonModule: "quant_learning.experiments",
    objectives: ["按年份分组收益", "观察 regime change", "识别稳定性问题"],
    concepts: ["yearly performance", "regime change", "stability"],
    intuition: "一个策略可能在趋势市场很好，在震荡市场很差。按年份拆开看，能避免平均数掩盖问题。",
    handExample: "全样本年化 12%，但其中一年 -25%、另一年 +40%，这比平稳每年 12% 风险大得多。",
    pythonCode: code.yearly,
    chart: "metrics",
    chartNote: "年度指标表帮助你观察收益是否集中在少数年份。",
    mistakes: ["只看全样本平均", "忽略市场环境变化", "把单一年份外推到未来"],
    checkpoint: ["能生成年度表现", "能解释 regime change", "知道平均数会掩盖路径"],
    quizQuestion: "分年度表现主要帮助你看什么？",
    correctLabel: "稳定性和环境差异",
    wrongLabels: ["保证明年收益", "替代样本外验证"],
    quizExplanation: "年度拆分能暴露表现是否集中在少数时期。",
    codexFunction: "yearly_performance",
    targetFile: "python/src/quant_learning/experiments.py",
    testFile: "python/tests/test_experiments.py",
  }),
);

lessons.push(
  makeLesson({
    id: "6.2",
    moduleId: "m6",
    order: 602,
    slug: "momentum-strategy",
    title: "动量策略",
    subtitle: "过去一段时间上涨，是否可能继续强势？这是动量的学习假设。",
    pythonModule: "quant_learning.strategies",
    objectives: ["理解 lookback", "计算过去收益作为动量分数", "实现单资产动量信号"],
    concepts: ["momentum", "lookback", "ranking", "trend continuation"],
    intuition: "动量策略假设强者可能继续强一段时间。但这只是市场假设，不是自然规律。你要把它当成一个可测试的学习想法，而不是看到过去上涨就默认未来继续上涨。",
    formula: "momentum_t = price_t / price_{t-lookback} - 1",
    handExample: "如果 20 天前价格 100，今天 110，20 日动量是 10%。",
    pythonCode: code.momentum,
    chart: "strategy-comparison",
    chartNote: "策略对比图展示动量和其他学习策略的净值路径差异。",
    mistakes: ["认为上涨一定会继续", "lookback 越长越好", "忘记样本外验证"],
    checkpoint: ["能解释动量假设", "能实现动量 signal", "知道动量会失效"],
    quizQuestion: "动量策略的核心假设是什么？",
    correctLabel: "过去强势可能延续",
    wrongLabels: ["下跌一定反弹", "交易成本为零"],
    quizExplanation: "动量研究的是趋势延续假设，但它不保证未来。",
    codexFunction: "momentum_signal",
    targetFile: "python/src/quant_learning/strategies.py",
    testFile: "python/tests/test_strategies.py",
  }),
  makeLesson({
    id: "6.3",
    moduleId: "m6",
    order: 603,
    slug: "mean-reversion-strategy",
    title: "均值回归策略",
    subtitle: "价格短期偏离均值后，是否可能回到均值附近？",
    pythonModule: "quant_learning.strategies",
    objectives: ["理解 rolling mean 和 z-score", "实现阈值型信号", "认识均值回归风险"],
    concepts: ["mean reversion", "rolling mean", "z-score", "threshold"],
    intuition: "均值回归像判断价格是不是短期跑太远了。但市场可能不是跑远，而是基本面真的变了。",
    formula: "z_score = (price - rolling_mean) / rolling_std",
    handExample: "如果价格低于滚动均值 2 个标准差，学习策略可能生成买入信号。",
    pythonCode: code.meanReversion,
    chart: "strategy-comparison",
    chartNote: "均值回归曲线和趋势类策略放在一起，帮助比较不同假设。",
    mistakes: ["下跌就认为一定反弹", "忽略趋势市场中的连续亏损", "阈值只按历史最好选择"],
    checkpoint: ["能解释 z-score", "能实现均值回归 signal", "能说出失效场景"],
    quizQuestion: "均值回归策略最大的误区是什么？",
    correctLabel: "以为下跌一定反弹",
    wrongLabels: ["需要日期索引", "要计算收益率"],
    quizExplanation: "价格偏离均值可能继续偏离，不能把反弹当成必然。",
    codexFunction: "mean_reversion_signal",
    targetFile: "python/src/quant_learning/strategies.py",
    testFile: "python/tests/test_strategies.py",
  }),
  makeLesson({
    id: "6.4",
    moduleId: "m6",
    order: 604,
    slug: "strategy-parameters",
    title: "策略参数和函数接口",
    subtitle: "策略函数要清楚、可测、参数非法时要明确拒绝。",
    pythonModule: "quant_learning.strategies",
    objectives: ["设计策略函数签名", "校验参数合法性", "保证返回索引对齐"],
    concepts: ["function interface", "parameter validation", "aligned signal"],
    intuition: "好的策略函数像一个稳定零件。它只生成信号，不偷偷跑回测，也不隐藏成本假设。",
    handExample: "双均线函数如果 fast_window=20、slow_window=10，就应该抛出清晰错误，而不是生成一个含糊结果。",
    pythonCode: code.movingAverage,
    chart: "moving-average",
    chartNote: "参数变化会影响信号图，但函数接口必须保持一致。",
    mistakes: ["策略函数里直接跑回测", "非法参数静默返回全 0", "返回索引和价格不一致"],
    checkpoint: ["能设计清晰函数签名", "能校验参数", "知道策略函数只输出 signal"],
    quizQuestion: "策略函数首要职责是什么？",
    correctLabel: "生成信号",
    wrongLabels: ["直接下单", "保证盈利"],
    quizExplanation: "课程项目中策略函数只生成学习型 signal，回测由 backtester 负责。",
    codexFunction: "策略参数校验",
    targetFile: "python/src/quant_learning/strategies.py",
    testFile: "python/tests/test_strategies.py",
  }),
  makeLesson({
    id: "6.5",
    moduleId: "m6",
    order: 605,
    slug: "strategy-comparison",
    title: "策略对比",
    subtitle: "公平比较要求同一数据、同一成本、同一回测器和同一指标。",
    pythonModule: "quant_learning.backtest",
    objectives: ["比较多个 BacktestResult", "加入 benchmark", "识别不公平比较"],
    concepts: ["strategy comparison", "benchmark", "same assumptions"],
    intuition: "策略对比像比赛。你不能让一个策略扣成本，另一个不扣；也不能让一个用复权价格，另一个用普通 close。",
    handExample: "比较 buy and hold 和双均线时，两者应使用同一段价格数据、同一 signal_lag=1 和同一成本设置，例如都扣 3 bps。",
    pythonCode: `def compare_strategies(results: dict[str, BacktestResult]) -> pd.DataFrame:\n    rows = []\n    for name, result in results.items():\n        rows.append({"name": name, **result.metrics})\n    return pd.DataFrame(rows).set_index("name")`,
    chart: "strategy-comparison",
    chartNote: "多策略净值图帮助看路径差异，但结论必须结合指标和假设。",
    mistakes: ["只比较最终收益", "每个策略用不同成本", "忘记 benchmark"],
    checkpoint: ["能公平比较策略", "知道需要 benchmark", "能读多策略净值图"],
    quizQuestion: "公平策略比较需要什么？",
    correctLabel: "相同数据和假设",
    wrongLabels: ["只看最高收益", "只看最短样本"],
    quizExplanation: "比较策略时，数据、成本和回测规则必须一致。",
    codexFunction: "compare_strategies",
    targetFile: "python/src/quant_learning/backtest.py",
    testFile: "python/tests/test_backtest.py",
  }),
  makeLesson({
    id: "7.1",
    moduleId: "m7",
    order: 701,
    slug: "multi-asset-alignment",
    title: "多股票数据对齐",
    subtitle: "多资产组合的第一步不是策略，而是把日期和列对齐。",
    pythonModule: "quant_learning.data",
    objectives: ["理解多资产日期交集", "处理缺失资产价格", "避免随意填补数据"],
    concepts: ["multi asset", "alignment", "missing data", "date intersection"],
    intuition: "多股票数据像几本日记。你要比较同一天的记录，不能把 A 股票周一的数据和 B 股票周二的数据混在一起。",
    handExample: "如果 AAPL 有 1 月 2 日价格，MSFT 没有这一日价格，组合收益要明确如何处理这个缺口。",
    pythonCode: `def align_price_data(prices: pd.DataFrame) -> pd.DataFrame:\n    return prices.sort_index().dropna(how="any")`,
    chart: "portfolio",
    chartNote: "多资产净值图只有在日期对齐后才有可比意义。",
    mistakes: ["随意前向填充所有缺失价格", "不同资产日期错位", "不记录删除了哪些日期"],
    checkpoint: ["能解释多资产对齐", "知道缺失值处理有风险", "能准备组合收益输入"],
    quizQuestion: "多股票组合前为什么要对齐日期？",
    correctLabel: "确保同一天收益可比较",
    wrongLabels: ["让图表颜色相同", "保证没有亏损"],
    quizExplanation: "组合收益需要同一日期上的资产收益和权重。",
    codexFunction: "align_price_data",
    targetFile: "python/src/quant_learning/data.py",
    testFile: "python/tests/test_data.py",
  }),
  makeLesson({
    id: "7.2",
    moduleId: "m7",
    order: 702,
    slug: "portfolio-returns",
    title: "组合收益",
    subtitle: "组合收益来自每个资产收益和权重的加权和。",
    pythonModule: "quant_learning.portfolio",
    objectives: ["理解资产权重", "计算等权组合收益", "手算两资产组合"],
    concepts: ["portfolio return", "weight", "equal weight"],
    intuition: "组合不是把股票名字放在一起，而是用权重决定每只资产对结果的贡献。同一只股票涨跌多少并不直接等于组合涨跌，关键要看它在组合里占了多少权重。",
    formula: "portfolio_return = sum(weight_i * return_i)",
    handExample: "AAPL +2%、MSFT -1%，各 50% 权重，组合收益是 +0.5%。",
    pythonCode: code.portfolio,
    chart: "portfolio",
    chartNote: "组合曲线通常不会等于任何单只股票，而是权重加权后的路径。",
    mistakes: ["把多只股票收益简单相加", "权重和不为 1", "忽略现金仓位"],
    checkpoint: ["能手算组合收益", "能实现等权收益", "知道权重决定贡献"],
    quizQuestion: "组合收益由什么决定？",
    correctLabel: "资产收益和权重",
    wrongLabels: ["股票名称长度", "交易所名称"],
    quizExplanation: "组合收益是各资产收益按权重加权后的结果。",
    codexFunction: "equal_weight_portfolio",
    targetFile: "python/src/quant_learning/portfolio.py",
    testFile: "python/tests/test_portfolio.py",
  }),
  makeLesson({
    id: "7.3",
    moduleId: "m7",
    order: 703,
    slug: "rebalancing",
    title: "再平衡",
    subtitle: "资产涨跌会让权重漂移，再平衡会把组合拉回目标权重。",
    pythonModule: "quant_learning.positions",
    objectives: ["理解权重漂移", "理解日度和月度再平衡", "知道再平衡也会产生成本"],
    concepts: ["rebalance", "weight drift", "turnover", "target weight"],
    intuition: "如果一只股票涨很多，它在组合里的比例会变大。再平衡就是定期把权重调回计划值。",
    handExample: "等权组合开始 A/B 各 50%，A 大涨后可能变成 60/40，再平衡会卖出部分 A、买入部分 B。",
    pythonCode: code.weights,
    chart: "portfolio",
    chartNote: "组合图可以观察不同资产涨跌如何影响整体路径。",
    mistakes: ["以为等权永远自动保持等权", "忽略再平衡成本", "每天再平衡但不扣成本"],
    checkpoint: ["能解释权重漂移", "知道再平衡会产生成本", "能把再平衡写进报告假设"],
    quizQuestion: "再平衡通常会带来什么副作用？",
    correctLabel: "交易成本和换手",
    wrongLabels: ["保证收益更高", "消除所有风险"],
    quizExplanation: "再平衡需要交易，交易会带来成本。",
    codexFunction: "rebalance_weights",
    targetFile: "python/src/quant_learning/positions.py",
    testFile: "python/tests/test_positions.py",
  }),
  makeLesson({
    id: "7.4",
    moduleId: "m7",
    order: 704,
    slug: "momentum-rotation",
    title: "多资产动量轮动",
    subtitle: "在多只股票中选择近期更强的资产，但排名也可能只是噪声。",
    pythonModule: "quant_learning.portfolio",
    objectives: ["理解横截面排名", "实现 top-n 选择", "识别排名策略风险"],
    concepts: ["ranking", "top-n", "rotation", "cash fallback"],
    intuition: "轮动策略像每段时间重新排队，选择近期表现靠前的资产。但排队靠前不代表下一段还靠前。",
    handExample: "如果 AAPL 20 日收益 8%、MSFT 3%、SPY 2%，top-1 动量轮动会选择 AAPL。",
    pythonCode: code.rotation,
    chart: "portfolio",
    chartNote: "多资产净值图让你比较单资产、等权和轮动的路径。",
    mistakes: ["排名第一就认为最安全", "频繁轮动但忽略成本", "没有和 SPY benchmark 比较"],
    checkpoint: ["能解释 top-n", "能实现轮动信号", "知道排名策略可能过拟合"],
    quizQuestion: "动量轮动策略选择资产的依据是什么？",
    correctLabel: "过去一段时间的排名",
    wrongLabels: ["公司名字排序", "未来已知收益"],
    quizExplanation: "轮动策略根据历史 lookback 表现排名，但未来未知。",
    codexFunction: "momentum_rotation_signal",
    targetFile: "python/src/quant_learning/portfolio.py",
    testFile: "python/tests/test_portfolio.py",
  }),
  makeLesson({
    id: "7.5",
    moduleId: "m7",
    order: 705,
    slug: "portfolio-vs-benchmark",
    title: "组合 vs SPY",
    subtitle: "组合策略必须和清晰基准比较，分散化也要看证据。",
    pythonModule: "quant_learning.portfolio",
    objectives: ["比较组合和 benchmark", "观察组合回撤", "判断分散化是否改善风险"],
    concepts: ["portfolio benchmark", "diversification", "SPY"],
    intuition: "买很多股票不自动等于分散化。如果它们高度同涨同跌，组合回撤可能仍然很大。",
    handExample: "如果组合年化收益 8% 低于 SPY 的 10%，但最大回撤是 -12% 而 SPY 是 -25%，它仍然有学习讨论价值。",
    pythonCode: `portfolio = equal_weight_portfolio(asset_returns)\nbenchmark = calculate_returns(spy_prices)\ncomparison = pd.DataFrame({"portfolio": portfolio, "SPY": benchmark}).dropna()`,
    chart: "portfolio",
    chartNote: "组合和 SPY 放在同一张图里，帮助观察收益和路径差异。",
    mistakes: ["组合只和现金比较", "股票数量多就宣称分散", "只看收益不看回撤"],
    checkpoint: ["能选择 benchmark", "能比较组合和 SPY", "知道分散化需要证据"],
    quizQuestion: "多股票组合一定更分散吗？",
    correctLabel: "不一定",
    wrongLabels: ["一定", "只要超过两只就一定"],
    quizExplanation: "如果资产高度相关，多股票组合也可能缺少真正分散化。",
    codexFunction: "组合 benchmark 报告",
    targetFile: "python/src/quant_learning/portfolio.py",
    testFile: "python/tests/test_portfolio.py",
  }),
);

lessons.push(
  makeLesson({
    id: "3.1",
    moduleId: "m3",
    order: 301,
    slug: "volatility",
    title: "波动率",
    subtitle: "波动率衡量收益变化幅度，不等于亏损，但会影响持有体验。",
    pythonModule: "quant_learning.metrics",
    objectives: ["理解收益率标准差", "计算年化波动率", "知道高收益高波动未必适合"],
    concepts: ["volatility", "standard deviation", "annualized volatility"],
    intuition: "两条净值曲线最终都到 1.2，但一条平稳上涨，另一条每天大起大落。波动率帮助描述这种不稳定程度。",
    formula: "annual_volatility = std(daily_returns) * sqrt(252)",
    handExample: "如果日收益经常在 +5% 和 -5% 之间跳动，哪怕最终收益不错，持有过程也会很难受。",
    pythonCode: code.volatility,
    chart: "volatility",
    chartNote: "收益率分布越分散，波动率越高。图表帮助你观察波动来自收益序列。",
    mistakes: ["把波动率当成最大亏损", "收益高就忽略波动", "用价格标准差替代收益率标准差"],
    checkpoint: ["能解释波动率", "能计算年化波动率", "知道波动率有局限"],
    quizQuestion: "波动率主要衡量什么？",
    correctLabel: "收益率变化幅度",
    wrongLabels: ["未来一定亏损", "股票成交量"],
    quizExplanation: "波动率描述收益率分散程度，不直接等同于亏损。",
    codexFunction: "annualized_volatility",
    targetFile: "python/src/quant_learning/metrics.py",
    testFile: "python/tests/test_metrics.py",
  }),
  makeLesson({
    id: "3.4",
    moduleId: "m3",
    order: 304,
    slug: "win-rate-profit-loss",
    title: "胜率和盈亏比",
    subtitle: "交易赢得多不一定赚钱，单次亏损大小同样关键。",
    pythonModule: "quant_learning.metrics",
    objectives: ["计算胜率", "计算盈亏比", "理解交易级指标的局限"],
    concepts: ["win rate", "average win", "average loss", "profit/loss ratio"],
    intuition: "胜率像考试答对题目的比例，盈亏比像答对一题加多少分、答错一题扣多少分。只看答对比例是不够的。",
    formula: "profit_loss_ratio = average_win / abs(average_loss)",
    handExample: "9 次赚 1 元、1 次亏 20 元，胜率 90%，但总结果是 -11 元。",
    pythonCode: code.winLoss,
    chart: "metrics",
    chartNote: "指标卡片提醒你同时看收益、风险和交易级指标。",
    mistakes: ["高胜率等于好策略", "只看平均盈利不看平均亏损", "把每日收益当作真实交易记录"],
    checkpoint: ["能计算胜率", "能解释盈亏比", "知道交易指标需要交易记录支持"],
    quizQuestion: "高胜率策略一定赚钱吗？",
    correctLabel: "不一定",
    wrongLabels: ["一定", "只要超过 50% 就一定"],
    quizExplanation: "如果亏损交易远大于盈利交易，高胜率也可能亏钱。",
    codexFunction: "win_rate 和 profit_loss_ratio",
    targetFile: "python/src/quant_learning/metrics.py",
    testFile: "python/tests/test_metrics.py",
  }),
  makeLesson({
    id: "3.5",
    moduleId: "m3",
    order: 305,
    slug: "read-metrics-table",
    title: "如何读一张指标表",
    subtitle: "指标表不是答案，它是一组帮助你追问的问题。",
    pythonModule: "quant_learning.metrics",
    objectives: ["组合阅读收益、波动、回撤和夏普", "识别单一指标盲点", "生成绩效摘要"],
    concepts: ["performance summary", "metric tradeoff", "risk adjusted return"],
    intuition: "指标表像体检报告。某一项正常不代表整体健康，某一项异常也需要结合上下文判断。",
    handExample: "策略 A 收益高但回撤 -40%，策略 B 收益低但回撤 -8%。哪个更好取决于目标和承受能力。",
    pythonCode: `def performance_summary(returns, equity=None) -> dict:\n    return {\n        "annualized_return": annualized_return(returns),\n        "annualized_volatility": annualized_volatility(returns),\n        "max_drawdown": max_drawdown(compound_returns(returns) if equity is None else equity),\n        "sharpe_ratio": sharpe_ratio(returns),\n    }`,
    chart: "metrics",
    chartNote: "多个指标放在一起，能帮助你看到策略表现的不同侧面。",
    mistakes: ["只按收益排序", "把夏普当作唯一标准", "不看样本长度和数据范围"],
    checkpoint: ["能读懂指标表", "能指出 3 个指标盲点", "知道指标要和图表一起看"],
    quizQuestion: "指标表最合理的作用是什么？",
    correctLabel: "帮助提出更好的问题",
    wrongLabels: ["证明未来收益", "替代数据检查"],
    quizExplanation: "指标表总结历史样本表现，但不能证明未来。",
    codexFunction: "performance_summary",
    targetFile: "python/src/quant_learning/metrics.py",
    testFile: "python/tests/test_metrics.py",
  }),
  makeLesson({
    id: "4.4",
    moduleId: "m4",
    order: 404,
    slug: "position-sizing",
    title: "仓位管理",
    subtitle: "信号回答买不买，仓位回答买多少。",
    pythonModule: "quant_learning.positions",
    objectives: ["理解 exposure 和 weight", "归一化权重", "区分满仓、空仓和部分仓位"],
    concepts: ["position sizing", "weight", "exposure", "cash"],
    intuition: "同一个买入信号，可以买 10%、50% 或 100%。仓位大小决定风险暴露，不能被信号函数偷偷决定。",
    formula: "portfolio_return_t = sum(weight_i * return_i)",
    handExample: "两只股票权重各 50%，当天分别 +2% 和 -1%，组合收益是 0.5*2% + 0.5*(-1%) = 0.5%。",
    pythonCode: code.weights,
    chart: "position",
    chartNote: "仓位图展示哪几天真正承担市场风险，以及暴露程度如何变化。",
    mistakes: ["信号正确就满仓", "权重总和超过 1 但不说明杠杆", "多资产权重没有归一化"],
    checkpoint: ["能区分信号和仓位大小", "能归一化权重", "知道仓位影响风险"],
    quizQuestion: "买入信号和仓位大小的关系是什么？",
    correctLabel: "信号不等于仓位大小",
    wrongLabels: ["买入信号必须满仓", "仓位不影响风险"],
    quizExplanation: "信号只是交易想法，仓位大小需要单独管理。",
    codexFunction: "normalize_weights",
    targetFile: "python/src/quant_learning/positions.py",
    testFile: "python/tests/test_positions.py",
  }),
  makeLesson({
    id: "4.5",
    moduleId: "m4",
    order: 405,
    slug: "wrong-backtest-demo",
    title: "一个故意错误的回测",
    subtitle: "亲眼看到 look-ahead bias 如何让曲线变漂亮。",
    pythonModule: "quant_learning.backtest",
    objectives: ["比较错误 shift 和正确 shift", "识别偷看未来", "用测试保护回测逻辑"],
    concepts: ["look-ahead bias", "wrong shift", "bias demo"],
    intuition: "错误回测最危险的地方是它通常不会报错，甚至会给你一条更漂亮的曲线。你需要用逻辑和测试发现它。",
    handExample: "如果第 1 天收盘后才知道价格上涨 5%，却让策略在第 1 天开盘前就持仓，这等于提前知道了当天结局。",
    pythonCode: code.backtest,
    chart: "costs",
    chartNote: "错误 shift 曲线故意画得更好，用来提醒你漂亮曲线可能来自错误逻辑。",
    mistakes: ["以为代码跑通就逻辑正确", "只看收益不看实现", "没有写滞后持仓测试"],
    checkpoint: ["能识别错误 shift", "能写测试验证滞后", "知道漂亮曲线可能是偏差"],
    quizQuestion: "为什么错误回测特别危险？",
    correctLabel: "它可能跑通且结果更好看",
    wrongLabels: ["它一定会报错", "它不能画图"],
    quizExplanation: "逻辑错误不一定导致程序错误，必须主动审查。",
    codexFunction: "回测偏差审查测试",
    targetFile: "python/tests/test_backtest.py",
    testFile: "python/tests/test_backtest.py",
  }),
  makeLesson({
    id: "5.3",
    moduleId: "m5",
    order: 503,
    slug: "backtest-result-object",
    title: "BacktestResult 结果对象",
    subtitle: "不要只保存一个最终收益，过程数据才方便检查。",
    pythonModule: "quant_learning.backtest",
    objectives: ["保存配置、收益、仓位、净值和指标", "理解结果对象的价值", "为报告和策略比较做准备"],
    concepts: ["dataclass", "BacktestResult", "config", "equity curve"],
    intuition: "只保存总收益像只保存考试总分。你不知道哪题错了，也不知道过程哪里有问题。",
    handExample: "如果策略总收益是 8%，你还需要知道它在哪些日期持仓、最大回撤是多少、是否扣了成本。",
    pythonCode: code.backtest,
    chart: "backtest",
    chartNote: "回测结果对象支撑图表、指标卡片和报告生成。",
    mistakes: ["只返回 float", "不保存 config", "不保存 strategy_returns"],
    checkpoint: ["能解释结果对象字段", "知道为什么保存过程数据", "能为报告提供输入"],
    quizQuestion: "为什么 BacktestResult 不应该只保存 total_return？",
    correctLabel: "无法审查收益路径",
    wrongLabels: ["total_return 不重要", "图表不需要数据"],
    quizExplanation: "总收益有用，但不足以检查路径、风险和实现逻辑。",
    codexFunction: "BacktestResult",
    targetFile: "python/src/quant_learning/backtest.py",
    testFile: "python/tests/test_backtest.py",
  }),
  makeLesson({
    id: "5.4",
    moduleId: "m5",
    order: 504,
    slug: "backtest-report",
    title: "回测报告",
    subtitle: "把结果写成可读、可复查、带风险声明的报告。",
    pythonModule: "quant_learning.reports",
    objectives: ["生成报告字典", "保存 JSON 或 Markdown", "在报告中包含风险声明"],
    concepts: ["report", "summary metrics", "disclaimer", "date range"],
    intuition: "报告不是宣传材料，而是研究记录。它应该说清楚数据、方法、结果和限制，让另一个人能复查你的假设、代码路径和风险声明，而不是只看到一张好看的收益图。",
    handExample: "一份合格报告会写：使用样例数据、信号滞后一日、成本 3 bps、历史结果不代表未来。",
    pythonCode: code.report,
    chart: "metrics",
    chartNote: "报告把指标卡片、净值曲线和回撤曲线组织成可复查材料。",
    mistakes: ["只写收益截图", "不写数据范围", "不写非投资建议声明"],
    checkpoint: ["能生成报告", "报告含风险声明", "知道报告是研究记录"],
    quizQuestion: "回测报告必须包含什么声明？",
    correctLabel: "不构成投资建议",
    wrongLabels: ["保证未来收益", "推荐买入股票"],
    quizExplanation: "本项目是教育项目，报告必须清楚说明边界。",
    codexFunction: "generate_backtest_report",
    targetFile: "python/src/quant_learning/reports.py",
    testFile: "python/tests/test_reports.py",
  }),
  makeLesson({
    id: "5.5",
    moduleId: "m5",
    order: 505,
    slug: "test-backtest-logic",
    title: "用测试保护回测逻辑",
    subtitle: "回测函数比普通函数更需要测试，因为错误结果常常看起来很合理。",
    pythonModule: "quant_learning.backtest",
    objectives: ["测试 signal lag", "测试成本扣减", "测试索引对齐", "测试空输入边界"],
    concepts: ["pytest", "regression test", "alignment test"],
    intuition: "回测测试不是为了追求覆盖率数字，而是为了防止最常见、最昂贵的逻辑错误。",
    handExample: "构造价格从 100 跳到 200，但信号第二天才出现。如果回测捕获了这段上涨，就说明它偷看了未来。",
    pythonCode: `def test_backtest_lags_signal():\n    prices = pd.Series([100.0, 200.0, 200.0])\n    signals = pd.Series([0.0, 1.0, 1.0])\n    result = run_backtest(prices, signals, BacktestConfig(signal_lag=1))\n    assert result.equity_curve.iloc[-1] == pytest.approx(1.0)`,
    chart: "bias",
    chartNote: "偏差检查图提醒你：测试要覆盖那些结果会被美化的错误。",
    mistakes: ["只测试正常上涨场景", "没有测试滞后", "没有测试成本影响"],
    checkpoint: ["能写滞后测试", "能写成本测试", "知道回测测试的核心风险"],
    quizQuestion: "回测测试最应该优先保护哪类问题？",
    correctLabel: "偷看未来和成本遗漏",
    wrongLabels: ["按钮颜色", "README 字数"],
    quizExplanation: "look-ahead bias 和成本遗漏会直接扭曲策略结果。",
    codexFunction: "关键回测测试",
    targetFile: "python/tests/test_backtest.py",
    testFile: "python/tests/test_backtest.py",
  }),
);

lessons.push(
  makeLesson({
    id: "9.1",
    moduleId: "m9",
    order: 901,
    slug: "backtest-biases",
    title: "常见回测偏差",
    subtitle: "回测最危险的问题，往往不是代码报错，而是代码逻辑看起来没问题。",
    pythonModule: "quant_learning.reports",
    objectives: ["识别 look-ahead bias", "理解 survivorship 和 selection bias", "建立偏差检查清单"],
    concepts: ["look-ahead bias", "survivorship bias", "selection bias", "data snooping"],
    intuition: "偏差会让历史结果比现实更漂亮。你要像审查实验一样审查回测，而不是把图表当结论。",
    handExample: "只选择 2026 年还存在的大公司做 2000-2025 年历史回测，会忽略过去失败或退市的公司，这就是幸存者偏差。",
    pythonCode: `BIAS_CHECKLIST = [\n    "signal 是否使用未来信息",\n    "样本是否只包含幸存资产",\n    "参数是否在全样本反复挑选",\n    "是否忽略交易成本和滑点",\n]`,
    chart: "bias",
    chartNote: "偏差检查图把常见问题放进同一张清单，方便审查报告。",
    mistakes: ["代码能跑就认为正确", "只看漂亮曲线", "不记录数据选择过程"],
    checkpoint: ["能列出 4 类偏差", "能审查 signal lag", "知道选择样本也会产生偏差"],
    quizQuestion: "只回测当前仍存在的大公司，可能有什么问题？",
    correctLabel: "幸存者偏差",
    wrongLabels: ["收益率定义错误", "代码不能运行"],
    quizExplanation: "只看幸存资产会让历史表现偏乐观。",
    codexFunction: "bias_checklist",
    targetFile: "docs/bias-checklist.md",
    testFile: "python/tests/test_reports.py",
  }),
  makeLesson({
    id: "9.2",
    moduleId: "m9",
    order: 902,
    slug: "backtest-not-future",
    title: "为什么回测不能代表未来收益",
    subtitle: "回测是历史实验，不是未来承诺。",
    pythonModule: "quant_learning.reports",
    objectives: ["理解市场环境变化", "理解执行和流动性限制", "写出严谨结论"],
    concepts: ["uncertainty", "market regime", "liquidity", "execution"],
    intuition: "市场不是固定物理实验。参与者、利率、政策、流动性和竞争都会变化，历史规律可能消失。",
    handExample: "一个策略在 2019-2021 年低利率牛市表现很好，不代表在 2022 年高利率震荡市仍然有效。",
    pythonCode: `conclusion = "该策略在样例历史数据中表现为正收益，但这不构成投资建议，也不代表未来收益。"` ,
    chart: "metrics",
    chartNote: "指标卡片只能总结历史样本，不能变成未来收益承诺。",
    mistakes: ["把历史最优写成未来推荐", "忽略流动性和执行", "不写限制条件"],
    checkpoint: ["能写严谨风险声明", "知道回测只是历史实验", "能把夸张结论改写为研究结论"],
    quizQuestion: "样本外表现好是否证明未来一定赚钱？",
    correctLabel: "不能",
    wrongLabels: ["可以保证", "只要夏普高就保证"],
    quizExplanation: "样本外仍然是历史验证，不是未来保证。",
    codexFunction: "风险声明改写",
    targetFile: "python/src/quant_learning/reports.py",
    testFile: "python/tests/test_reports.py",
  }),
  makeLesson({
    id: "9.3",
    moduleId: "m9",
    order: 903,
    slug: "paper-trading-vs-live",
    title: "Paper Trading 和实盘交易",
    subtitle: "模拟记录信号和真实资金执行，是两件不同的事情。",
    pythonModule: "quant_learning.reports",
    objectives: ["区分 paper trading 和 live trading", "理解执行差异", "实现只记录信号的 logger"],
    concepts: ["paper trading", "live trading", "execution", "latency", "psychology"],
    intuition: "paper trading 可以帮助观察信号流程，但没有真实成交、滑点、心理压力和资金风险。",
    handExample: "模拟日志写着 09:30 出现买入信号，不代表真实账户能以 100.00 的理想价格成交，实盘可能成交在 100.20。",
    pythonCode: code.paperLog,
    chart: "learning-path",
    chartNote: "流程图展示研究、回测、模拟和实盘之间的边界。本项目停在学习和模拟记录。",
    mistakes: ["paper trading 盈利就等于实盘盈利", "把日志当订单", "忽略真实执行"],
    checkpoint: ["能解释 paper 和 live 区别", "知道本项目不下单", "能实现信号日志"],
    quizQuestion: "paper trading 和实盘的关键差异是什么？",
    correctLabel: "没有真实成交和资金风险",
    wrongLabels: ["一定收益更低", "不需要数据"],
    quizExplanation: "paper trading 是模拟记录，不能替代真实执行环境。",
    codexFunction: "paper_signal_log",
    targetFile: "python/src/quant_learning/reports.py",
    testFile: "python/tests/test_reports.py",
  }),
  makeLesson({
    id: "9.4",
    moduleId: "m9",
    order: 904,
    slug: "capstone-research-report",
    title: "Capstone：完整策略研究报告",
    subtitle: "把数据、策略、回测、参数验证和限制条件组织成一份学习报告。",
    pythonModule: "quant_learning.reports",
    objectives: ["完成一份完整研究报告", "包含图表、指标、成本和样本外", "写明至少 5 条限制"],
    concepts: ["capstone", "research report", "limitations", "reproducibility"],
    intuition: "最终报告不是为了证明策略好，而是为了证明你能完整、诚实、可复查地研究一个策略想法。",
    handExample: "报告应包含 5 类核心材料：数据来源、策略假设、回测配置、参数扫描、样本外结果和风险声明。",
    pythonCode: code.report,
    chart: "strategy-comparison",
    chartNote: "Capstone 页面应同时展示策略对比和关键指标，而不是只展示一张漂亮净值曲线。",
    mistakes: ["只写结论不写方法", "只展示最好参数", "没有风险声明"],
    checkpoint: ["能交付完整报告", "能说明限制条件", "Python 测试全部通过"],
    quizQuestion: "Capstone 报告的目标是什么？",
    correctLabel: "可复查地研究策略想法",
    wrongLabels: ["证明未来盈利", "推荐某只股票"],
    quizExplanation: "Capstone 是学习型研究报告，不是投资推荐。",
    codexFunction: "final_research_report",
    targetFile: "reports/final_research_report.md",
    testFile: "python/tests/test_reports.py",
  }),
  makeLesson({
    id: "9.5",
    moduleId: "m9",
    order: 905,
    slug: "next-roadmap",
    title: "量化学习的下一步路线",
    subtitle: "先把基础打牢，再进入因子、组合优化和更真实的回测系统。",
    pythonModule: "docs/course-design.md",
    objectives: ["规划后续学习", "识别需要补的数学和工程能力", "避免过早追复杂模型"],
    concepts: ["statistics", "time series", "factor research", "portfolio construction", "event-driven backtesting"],
    intuition: "量化学习不是从复杂模型开始，而是从数据、指标、验证和风险意识开始。基础稳，后面的模型才有意义。",
    handExample: "下一阶段可以先安排 3 个月路线：第 1 个月补统计，第 2 个月学时间序列，第 3 个月做因子研究小项目。",
    pythonCode: `NEXT_STEPS = [\n    "统计和概率基础",\n    "时间序列分析",\n    "因子研究入门",\n    "投资组合构建",\n    "事件驱动回测系统",\n]`,
    chart: "learning-path",
    chartNote: "学习路线图帮助你从当前项目自然扩展到下一阶段。",
    mistakes: ["过早追求复杂模型", "跳过数据质量和验证", "把策略收益当作学习唯一目标"],
    checkpoint: ["知道下一步学什么", "能选择一个扩展方向", "保持非投资建议边界"],
    quizQuestion: "下一阶段学习前最应该保留什么习惯？",
    correctLabel: "验证和风险意识",
    wrongLabels: ["只看收益最高", "跳过测试"],
    quizExplanation: "无论模型多复杂，验证、测试和风险边界都必须保留。",
    codexFunction: "个人下一步学习计划",
    targetFile: "docs/next-roadmap.md",
    testFile: "无需测试",
  }),
);

const modulesMeta = [
  {
    id: "m0",
    title: "Module 0: 学习方式和项目边界",
    summary: "先理解课程边界，再学会让 Codex 带着验收标准写代码。",
    product: "学习计划、风险声明、第一个收益率函数",
    miniProject: {
      title: "学习边界和第一条 Codex 工单",
      deliverable: "生成 learning-notes.md，记录项目边界、第一条 Prompt 和第一个已测试函数。",
      checks: ["说明非投资建议边界", "写出 Explain -> Implement -> Test -> Reflect 流程", "至少包含一个 pytest 结果"],
    },
    gate: {
      entry: "能打开项目并理解这是教育用途的学习站。",
      exit: "写下非投资建议边界，完成第一条带验收的 Codex Prompt。",
      nextUse: "Module 1 会沿用这个 Prompt 格式来读取和检查本地样例数据。",
    },
  },
  {
    id: "m1",
    title: "Module 1: 美股数据入门",
    summary: "读懂 ticker、交易日、OHLCV、复权价格和数据质量。",
    product: "数据读取函数和质量报告",
    miniProject: {
      title: "样例价格数据质量报告",
      deliverable: "生成 sample_prices_quality_report.json，并在报告里解释 close 与 adj_close 的选择。",
      checks: ["检查 OHLCV 必要列", "报告缺失值和重复日期", "说明复权价格用途"],
    },
    gate: {
      entry: "已经知道项目不联网、不连接账户，只使用本地样例数据。",
      exit: "生成数据质量报告，能解释 OHLCV、交易日缺口和复权列选择。",
      nextUse: "Module 2 会把这条可信价格序列转换成收益率和净值曲线。",
    },
  },
  {
    id: "m2",
    title: "Module 2: 收益和净值",
    summary: "从价格序列得到收益率、复利、年化收益和净值曲线。",
    product: "收益率和净值曲线函数",
    miniProject: {
      title: "价格到净值曲线",
      deliverable: "从样例价格生成日收益率、总收益和净值曲线数据。",
      checks: ["首日收益处理清楚", "复利用累乘而不是累加", "解释短样本年化风险"],
    },
    gate: {
      entry: "已经有经过基础检查的价格序列和复权列选择。",
      exit: "实现收益率、复利、年化和净值函数，并能手算一个小例子。",
      nextUse: "Module 3 会用收益路径计算波动、回撤、夏普和交易级指标。",
    },
  },
  {
    id: "m3",
    title: "Module 3: 风险和绩效指标",
    summary: "用回撤、夏普、胜率和盈亏比评价策略表现。",
    product: "风险指标计算模块和绩效摘要表",
    miniProject: {
      title: "绩效指标卡片",
      deliverable: "为 buy and hold 样例生成收益、波动率、最大回撤、夏普、胜率和盈亏比摘要。",
      checks: ["最大回撤从净值曲线计算", "零波动夏普有明确行为", "指出至少 3 个指标盲点"],
    },
    gate: {
      entry: "已经能从价格得到收益率和净值曲线。",
      exit: "生成绩效指标表，能指出最终收益、夏普和胜率的局限。",
      nextUse: "Module 4 会把这些指标连接到 signal、position、成本和偏差诊断。",
    },
  },
  {
    id: "m4",
    title: "Module 4: 信号、仓位和成本",
    summary: "把策略想法转换成现实一点的持仓和成本模型。",
    product: "position 和 transaction cost 模块",
    miniProject: {
      title: "信号、仓位和成本对比",
      deliverable: "比较同一信号在无成本、有成本、错误 shift、正确 shift 下的净值差异。",
      checks: ["position 默认滞后一日", "成本用 bps 表示", "解释 look-ahead bias"],
    },
    gate: {
      entry: "已经能读懂收益、回撤和指标表。",
      exit: "实现 signal -> position、turnover、cost，并能识别 look-ahead 示例。",
      nextUse: "Module 5 会把这些执行假设固化到统一回测器里。",
    },
  },
  {
    id: "m5",
    title: "Module 5: 第一套回测系统",
    summary: "把数据、信号、仓位、成本、净值和指标串成回测器。",
    product: "BacktestResult 和报告",
    miniProject: {
      title: "Buy and Hold 回测报告",
      deliverable: "运行 SPY 样例 buy and hold 回测，输出 JSON 或 Markdown 报告。",
      checks: ["保存 BacktestResult 过程数据", "报告包含成本配置", "报告包含非投资建议声明"],
    },
    gate: {
      entry: "已经有数据、收益、指标、仓位和成本函数。",
      exit: "运行 buy and hold 回测，产出含回撤、指标和风险声明的报告。",
      nextUse: "Module 6 会用同一回测器公平比较多个策略信号。",
    },
  },
  {
    id: "m6",
    title: "Module 6: 入门策略模式",
    summary: "用同一套回测器比较双均线、动量和均值回归。",
    product: "可测试的策略函数库和策略对比实验",
    miniProject: {
      title: "三类入门策略对比",
      deliverable: "在同一资产上比较 buy and hold、双均线、动量和均值回归。",
      checks: ["策略函数只生成 signal", "使用同一回测配置", "写出每个策略的假设和失效场景"],
    },
    gate: {
      entry: "已经有统一回测器和 buy and hold 基准报告。",
      exit: "用同一数据、lag、成本和指标公平比较三类策略。",
      nextUse: "Module 7 会把单资产策略比较扩展到多资产组合和 benchmark。",
    },
  },
  {
    id: "m7",
    title: "Module 7: 多股票组合",
    summary: "理解组合收益、权重、再平衡和 benchmark。",
    product: "等权组合和轮动组合实验",
    miniProject: {
      title: "组合和 SPY 基准比较",
      deliverable: "比较单股票、等权组合、动量轮动组合和 SPY benchmark。",
      checks: ["多资产日期已对齐", "组合收益按权重计算", "分散化结论有指标支持"],
    },
    gate: {
      entry: "已经会做单资产策略对比和基准比较。",
      exit: "对齐多资产数据，生成等权或轮动组合报告。",
      nextUse: "Module 8 会检查策略和组合参数在样本外是否还能迁移。",
    },
  },
  {
    id: "m8",
    title: "Module 8: 参数实验和验证",
    summary: "用参数扫描、样本外验证和随机策略识别过拟合风险。",
    product: "参数扫描和样本外报告",
    miniProject: {
      title: "参数扫描和样本外验证",
      deliverable: "扫描双均线参数，选择样本内最优参数，并展示样本外表现。",
      checks: ["跳过非法参数组合", "按日期切分样本", "说明历史最优不代表未来"],
    },
    gate: {
      entry: "已经有策略和组合实验结果。",
      exit: "展示参数扫描、样本内 / 外、随机策略或年度稳定性诊断。",
      nextUse: "Module 9 会把验证材料写入最终 Capstone 报告的限制和偏差章节。",
    },
  },
  {
    id: "m9",
    title: "Module 9: 回测边界和 Capstone",
    summary: "理解回测不能代表未来，并完成最终学习报告。",
    product: "包含数据、策略、验证和风险声明的完整研究报告",
    miniProject: {
      title: "Capstone 最终研究报告",
      deliverable: "提交 final_research_report.md，包含数据、策略、指标、成本、参数、样本外、偏差和风险声明。",
      checks: ["至少 5 条限制或风险", "包含 benchmark", "不包含投资建议或收益承诺"],
    },
    gate: {
      entry: "已经完成数据、指标、策略、组合和验证模块材料。",
      exit: "交付完整 Capstone 报告，并通过 Python 报告验证函数。",
      nextUse: "后续学习可以进入因子研究、事件驱动回测或组合优化，但继续保留验证和风险边界。",
    },
  },
];

export const courseModules: CourseModule[] = modulesMeta.map((module) => ({
  ...module,
  skillLines: moduleSkillLines[module.id] ?? [],
  lessons: lessons.filter((lesson) => lesson.moduleId === module.id),
}));

export const allLessons = [...lessons].sort((a, b) => a.order - b.order);

export function getLesson(slug: string) {
  return allLessons.find((lesson) => lesson.slug === slug);
}

export function getAdjacentLessons(slug: string) {
  const index = allLessons.findIndex((lesson) => lesson.slug === slug);
  return {
    previous: index > 0 ? allLessons[index - 1] : undefined,
    next: index >= 0 && index < allLessons.length - 1 ? allLessons[index + 1] : undefined,
  };
}

export function getModule(moduleId: string) {
  return courseModules.find((module) => module.id === moduleId);
}

export function getSkillLine(skillLineId: SkillLineId) {
  return skillLines.find((skillLine) => skillLine.id === skillLineId);
}
