import { defineLesson } from "../course/define-lesson";

export default defineLesson({
  id: "9.2",
  moduleId: "m9",
  order: 902,
  slug: "backtest-not-future",
  title: "为什么回测不能代表未来收益",
  subtitle: "回测是历史实验，不是未来承诺。",
  pythonModule: "quant_learning.reports",
  objectives: ["理解市场环境变化", "理解执行和流动性限制", "写出严谨结论"],
  concepts: ["uncertainty", "market regime", "liquidity", "execution"],
  intuition: "市场不是固定物理实验。参与者、利率、政策、流动性和竞争都会变化，历史规律可能消失。",
  handExample: "一个策略在 2019-2021 年低利率牛市表现很好，不代表在 2022 年高利率震荡市仍然有效。",
  pythonCode: "conclusion = \"该策略在样例历史数据中表现为正收益，但这不构成投资建议，也不代表未来收益。\"",
  chart: "metrics",
  chartNote: "指标卡片只能总结历史样本，不能变成未来收益承诺。",
  mistakes: ["把历史最优写成未来推荐", "忽略流动性和执行", "不写限制条件"],
  checkpoint: ["能写严谨风险声明", "知道回测只是历史实验", "能把夸张结论改写为研究结论"],
  skillLine: "research-writing",
  quizQuestion: "样本外表现好是否证明未来一定赚钱？",
  correctLabel: "不能",
  wrongLabels: ["可以保证", "只要夏普高就保证"],
  quizExplanation: "样本外仍然是历史验证，不是未来保证。",
  codexFunction: "风险声明改写",
  targetFile: "python/src/quant_learning/reports.py",
  testFile: "python/tests/test_reports.py",
});
