import { defineLesson } from "../course/define-lesson";

export default defineLesson({
  id: "9.5",
  moduleId: "m9",
  order: 905,
  slug: "next-roadmap",
  title: "量化学习的下一步路线",
  subtitle: "先把基础打牢，再进入因子、组合优化和更真实的回测系统。",
  pythonModule: "docs/course-design.md",
  objectives: ["规划后续学习", "识别需要补的数学和工程能力", "避免过早追复杂模型"],
  concepts: [
    "statistics",
    "time series",
    "factor research",
    "portfolio construction",
    "event-driven backtesting",
  ],
  intuition: "量化学习不是从复杂模型开始，而是从数据、指标、验证和风险意识开始。基础稳，后面的模型才有意义。",
  handExample: "下一阶段可以先安排 3 个月路线：第 1 个月补统计，第 2 个月学时间序列，第 3 个月做因子研究小项目。",
  pythonCode: `NEXT_STEPS = [
    "统计和概率基础",
    "时间序列分析",
    "因子研究入门",
    "投资组合构建",
    "事件驱动回测系统",
]`,
  chart: "learning-path",
  chartNote: "学习路线图帮助你从当前项目自然扩展到下一阶段。",
  mistakes: ["过早追求复杂模型", "跳过数据质量和验证", "把策略收益当作学习唯一目标"],
  checkpoint: ["知道下一步学什么", "能选择一个扩展方向", "保持非投资建议边界"],
  skillLine: "research-writing",
  quizQuestion: "下一阶段学习前最应该保留什么习惯？",
  correctLabel: "验证和风险意识",
  wrongLabels: ["只看收益最高", "跳过测试"],
  quizExplanation: "无论模型多复杂，验证、测试和风险边界都必须保留。",
  codexFunction: "个人下一步学习计划",
  targetFile: "docs/next-roadmap.md",
  testFile: "无需测试",
});
