import { defineLesson } from "../course/define-lesson";

export default defineLesson({
  id: "9.3",
  moduleId: "m9",
  order: 903,
  slug: "paper-trading-vs-live",
  title: "Paper Trading 和实盘交易",
  subtitle: "模拟记录信号和真实资金执行，是两件不同的事情。",
  pythonModule: "quant_learning.reports",
  objectives: ["区分 paper trading 和 live trading", "理解执行差异", "实现只记录信号的 logger"],
  concepts: ["paper trading", "live trading", "execution", "latency", "psychology"],
  intuition: "paper trading 可以帮助观察信号流程，但没有真实成交、滑点、心理压力和资金风险。",
  handExample: "模拟日志写着 09:30 出现买入信号，不代表真实账户能以 100.00 的理想价格成交，实盘可能成交在 100.20。",
  pythonCode: `def paper_signal_log(date, symbol: str, signal: float, reason: str) -> dict:
    return {
        "date": str(pd.Timestamp(date).date()),
        "symbol": symbol,
        "signal": float(signal),
        "reason": reason,
        "note": "paper log only; no order is sent",
    }`,
  chart: "learning-path",
  chartNote: "流程图展示研究、回测、模拟和实盘之间的边界。本项目停在学习和模拟记录。",
  mistakes: ["paper trading 盈利就等于实盘盈利", "把日志当订单", "忽略真实执行"],
  checkpoint: ["能解释 paper 和 live 区别", "知道本项目不下单", "能实现信号日志"],
  skillLine: "research-writing",
  quizQuestion: "paper trading 和实盘的关键差异是什么？",
  correctLabel: "没有真实成交和资金风险",
  wrongLabels: ["一定收益更低", "不需要数据"],
  quizExplanation: "paper trading 是模拟记录，不能替代真实执行环境。",
  codexFunction: "paper_signal_log",
  targetFile: "python/src/quant_learning/reports.py",
  testFile: "python/tests/test_reports.py",
});
