import { defineLesson } from "../course/define-lesson";

export default defineLesson({
  id: "0.1",
  moduleId: "m0",
  order: 1,
  slug: "project-boundary",
  title: "这门课学什么，不学什么",
  subtitle: "先把边界说清楚：这是学习项目，不是赚钱系统。",
  difficulty: "入门",
  duration: "8 分钟",
  pythonModule: "README.md",
  objectives: ["区分量化研究、回测、paper trading 和实盘交易", "理解为什么课程不会提供投资建议", "知道最终会完成一个学习型研究报告"],
  concepts: ["量化研究", "回测", "paper trading", "实盘交易", "非投资建议"],
  intuition: "量化学习像是在实验室里研究问题。你会写代码、看数据、画图、检查假设，但实验室结果不能直接等同于真实市场里的资金结果。",
  handExample: "如果一个策略在历史数据上从 1.00 涨到 1.20，这只能说明它在这段历史样本里的回测净值上涨了 20%，不能说明未来也会上涨 20%。",
  pythonCode: "PROJECT_BOUNDARY = \"education only, not investment advice\"",
  chart: "learning-path",
  chartNote: "学习路径图把课程分成数据、指标、仓位、回测、策略、验证和报告几个阶段。",
  mistakes: ["把回测截图当成收益承诺", "没理解交易成本和执行问题就谈实盘", "只追求策略收益，不学习验证方法"],
  checkpoint: ["能说出本项目不是投资建议", "能解释回测和实盘的区别", "知道课程最终产物是一份学习报告"],
  skillLine: "research-writing",
  quizQuestion: "这门课里的双均线策略应该被理解为什么？",
  correctLabel: "学习案例",
  wrongLabels: ["投资建议", "保证盈利的方法"],
  quizExplanation: "课程策略只用于学习如何编码、回测和审查假设，不构成投资建议。",
  codexFunction: "项目风险声明",
  targetFile: "README.md",
  testFile: "无需测试",
});
